### ISSUE TITLE
Permission denied: '/etc/receptor/receptor.conf.lock'

### ISSUE THREAD

**Issue by a-dawg** [ansible/tower-operator#1094]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

using the awx operator  and awx version 21.7.0 I am getting the error below: 
`````
2022-10-20 08:58:25,384 ERROR    [-] awx.main.dispatch Encountered unhandled error in dispatcher main loop
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/base.py", line 172, in run
    self.worker.on_start()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 140, in on_start
    dispatch_startup()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 86, in dispatch_startup
    write_receptor_config()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 653, in write_receptor_config
    with lock:
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/filelock/_api.py", line 220, in __enter__
    self.acquire()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/filelock/_api.py", line 173, in acquire
    self._acquire()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/filelock/_unix.py", line 35, in _acquire
    fd = os.open(self._lock_file, open_mode)
PermissionError: [Errno 13] Permission denied: '/etc/receptor/receptor.conf.lock'
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 201, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_dispatcher.py", line 81, in handle
    consumer.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/base.py", line 172, in run
    self.worker.on_start()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 140, in on_start
    dispatch_startup()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 86, in dispatch_startup
    write_receptor_config()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 653, in write_receptor_config
    with lock:
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/filelock/_api.py", line 220, in __enter__
    self.acquire()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/filelock/_api.py", line 173, in acquire
    self._acquire()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/filelock/_unix.py", line 35, in _acquire
    fd = os.open(self._lock_file, open_mode)
PermissionError: [Errno 13] Permission denied: '/etc/receptor/receptor.conf.lock'
`````
### AWX Operator version

0.28.0

### AWX version

21.7.0

### Kubernetes platform

openshift

### Kubernetes/Platform version

4.10

### Modifications

no

### Steps to reproduce

install the awx operator and create an awx instance with:
`````
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: lo-awx
  namespace: awx-operator
spec:
  admin_password_secret: awx-admin-password
  ingress_type: route
  postgres_image: xxxxx/postgres
  postgres_image_version: "14"
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: false
  loadbalancer_port: 80
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  auto_upgrade: true
  task_privileged: false
  control_plane_ee_image: 'quay.io/ansible/awx-ee:0.6.0'
  redis_image_version: 7.0.3
  hostname: awx.xxxx
  image_version: 21.7.0
  set_self_labels: true
  redis_image:xxxx/redis
  ee_images:
    - image: 'xxx/ansible-exec:openshift-latest'
      name: openshift
  no_log: 'false'
  postgres_storage_requirements:
    limits:
      storage: 10Gi
    requests:
      storage: 1Gi
  projects_persistence: false
  postgres_resource_requirements:
    limits:
      cpu: '1'
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  image: xxxx/ansible/awx
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  nodeport_port: 30080
  route_host: xxxx
`````

### Expected results

the instance runs correctly

### Actual results

503 error the awx-task container is crashing with error above

**Comment by gdlx** [comment]
Also have the issue when switching to 21.7.0.
Seems to be related to this change: https://github.com/ansible/awx/pull/12890
But I have this error while being on K8s...

**Comment by adpavlov** [comment]
I'm facing similar issue with `awx-operator:0.30.0`, but for `/etc/receptor/receptor.conf`

```
2022-10-29 18:09:15,891 INFO spawned: 'dispatcher' with pid 61
2022-10-29 18:09:15,891 INFO spawned: 'dispatcher' with pid 61
2022-10-29 15:09:18,190 WARNING  [-] awx.main.dispatch.periodic periodic beat started
2022-10-29 15:09:18,226 INFO     [-] awx.main.dispatch Running worker dispatcher listening to queues ['tower_broadcast_all', 'awx-574448576b-clrst']
2022-10-29 15:09:18,279 ERROR    [-] awx.main.dispatch Encountered unhandled error in dispatcher main loop
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/base.py", line 172, in run
    self.worker.on_start()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 140, in on_start
    dispatch_startup()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 86, in dispatch_startup
    write_receptor_config()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 668, in write_receptor_config
    with open(__RECEPTOR_CONF, 'w') as file:
PermissionError: [Errno 13] Permission denied: '/etc/receptor/receptor.conf'
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 201, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_dispatcher.py", line 81, in handle
    consumer.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/base.py", line 172, in run
    self.worker.on_start()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 140, in on_start
    dispatch_startup()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 86, in dispatch_startup
    write_receptor_config()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 668, in write_receptor_config
    with open(__RECEPTOR_CONF, 'w') as file:
PermissionError: [Errno 13] Permission denied: '/etc/receptor/receptor.conf'
```

**Comment by TheRealHaoLiu** [comment]
FYI @fosterseth @shanemcd

**Comment by fosterseth** [comment]
@a-dawg @gdlx @adpavlov what does `ls -la /etc/receptor` give you on the awx-task container?

```
bash-5.1$ ls -la /etc/receptor
total 4
drwxrwxrwx 1 root root 124 Oct 28 18:33 .
drwxr-xr-x 1 root root  38 Nov  1 16:40 ..
-rw-r--r-- 1 awx  root 962 Nov  1 16:40 receptor.conf
-rwxr-xr-x 1 awx  root   0 Nov  1 16:46 receptor.conf.lock
-rwxr-xr-x 1 root root   0 Oct 28 18:32 receptor-default.conf
drwxr-xr-x 1 root root  40 Oct 28 18:32 signing
drwxr-xr-x 1 root root   0 Oct 28 18:32 tls
bash-5.1$ whoami
awx
```

for me that directory has full read/write permissions.

**Comment by adpavlov** [comment]
> @a-dawg @gdlx @adpavlov what does `ls -la /etc/receptor` give you on the awx-task container?
> 
> ```
> bash-5.1$ ls -la /etc/receptor
> total 4
> drwxrwxrwx 1 root root 124 Oct 28 18:33 .
> drwxr-xr-x 1 root root  38 Nov  1 16:40 ..
> -rw-r--r-- 1 awx  root 962 Nov  1 16:40 receptor.conf
> -rwxr-xr-x 1 awx  root   0 Nov  1 16:46 receptor.conf.lock
> -rwxr-xr-x 1 root root   0 Oct 28 18:32 receptor-default.conf
> drwxr-xr-x 1 root root  40 Oct 28 18:32 signing
> drwxr-xr-x 1 root root   0 Oct 28 18:32 tls
> bash-5.1$ whoami
> awx
> ```
> 
> for me that directory has full read/write permissions.

I did even scratch installation and permissions are almost same except owner of `receptor.conf`. For me owner is `root` and not `awx` comparing to yours.

```
kubectl -n awx exec awx-574448576b-p9s54 -c awx-task -- ls -la /etc/receptor
total 20
drwxrwsrwx 4 root 1000 4096 Nov  2 08:43 .
drwxr-xr-x 1 root root 4096 Nov  2 08:43 ..
-rw-r--r-- 1 root 1000  965 Nov  2 08:40 receptor.conf
-rwxr-xr-x 1 awx  1000    0 Nov  2 08:43 receptor.conf.lock
-rwxr-xr-x 1 root 1000    0 Nov  2 08:40 receptor-default.conf
drwxr-sr-x 2 root 1000 4096 Nov  2 08:40 signing
drwxr-sr-x 2 root 1000 4096 Nov  2 08:40 tls
```

I checked my deployments on awx 21.6.0 and operator 0.29.0, owner is `root` for both `receptor.conf` and `receptor.conf`

There are arguments in awx-ee container. MIght be this is causing owner change?

```
/bin/sh
-c
if [ ! -f /etc/receptor/receptor.conf ]; then
  cp /etc/receptor/receptor-default.conf /etc/receptor/receptor.conf
  sed -i "s/HOSTNAME/$HOSTNAME/g" /etc/receptor/receptor.conf
fi
exec receptor --config /etc/receptor/receptor.conf
```

**Comment by adpavlov** [comment]
@fosterseth @shanemcd  
if I change `/etc/receptor/receptor.conf` permissions in `awx-ee` container to `777` `awx-task` container successfully starts

**Comment by fosterseth** [comment]
@adpavlov @gdlx @a-dawg which versions of operator are you on?

awx v21.6+ is going to require awx-operator v0.29.0+

can you please try with on later operator versions and see if the problem persists?

**Comment by adpavlov** [comment]
> @adpavlov @gdlx @a-dawg which versions of operator are you on?
> 
> 
> 
> awx v21.6+ is going to require awx-operator v0.29.0+
> 
> 
> 
> can you please try with on later operator versions and see if the problem persists?

I used latest 21.7.0 and 1.0.0

**Comment by TheRealHaoLiu** [comment]
i have not been able to reproduce this problem on kind or OpenShift can someone help test out this PR that @fosterseth tossed up (with instruction to test and reproduce) https://github.com/ansible/awx-operator/pull/1110

also we can be found on https://matrix.to/#/#awx:ansible.com if anyone wanna come collaborate on this issue

**Comment by adpavlov** [comment]
my issue was caused by wrong user in container. I'm building custom image and used root for some commands. Once I add user 1000 issue resolved.

**Comment by wupeng606** [comment]
> 

I am facing this problem with okd/openshift 4.9.37, awx 21.9.0, awx-operator 1.1.0.

**Comment by gdlx** [comment]
> @a-dawg @gdlx @adpavlov what does `ls -la /etc/receptor` give you on the awx-task container?

Here's what I get:
```
bash-5.1$ ls -la /etc/receptor
total 4
drwxr-xr-x 2 root root  27 Dec  6 10:53 .
drwxr-xr-x 1 root root  49 Dec  6 10:53 ..
-rw-r--r-- 1 root bin  592 Dec  6 10:53 receptor.conf
```

I still have the error on 21.10.0.
Not sure which awx-operator version is used, I don't customize it and I don't customize the image.
Awx EE tag is `latest`.

**Comment by melslow** [comment]
Facing the same issue on k8s operator version 1.1.0 and awx version 21.9.0

**Comment by melslow** [comment]
For what its worth i was able to fix this issue by using the latest EE image.

**Comment by fosterseth** [comment]
we haven't heard or seen reports of this in the past few months, let's close for now and if people experience this error again, let's reopen a new issue

**Comment by vshete93** [comment]
@fosterseth looks like if I use init_container_image_version:"tag_number" awx-ee has above issue spinning up. However init container doesnt start irrespective of what tag I use (latest or tag_number). What can be the issue here?

**Comment by vshete93** [comment]
Also below are the permissions on task container which looks quite different than what it needs to be. This is when init_image being used with latest tag

`-rw-r--r-- 1 systemd-coredump systemd-coredump 992 Jun 15 18:35 receptor.conf`

This is for awx-ee container

`-rw-r--r-- 1 tower_user awx_tower 992 Jun 15 18:35 receptor.conf` . `tower_user` came out of custom image build for awx-ee image.

**Comment by golakiyaalice** [comment]
I am trying to configure excutor in service mesh on a VM is different region than my AWX.
I am facing below error.

root@******:/etc/receptor# /usr/bin/receptor -c /etc/receptor/receptor.conf
Error: error opening Unix socket: could not acquire lock on socket file: fslock is already locked
