### ISSUE TITLE
Fresh AWX Operator cant start Jobs on EKS 1.22

### ISSUE THREAD

**Issue by henrysachs** [ansible/tower-operator#1138]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I deployed the Operator according to the "basic install" section and tried to start the sample jobs. But after that no pods in kubernetes are started and i receive the following error: 

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 485, in run
    self.build_project_dir(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 1066, in build_project_dir
    self.sync_and_copy(job.project, private_data_dir, scm_branch=job.scm_branch)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 774, in sync_and_copy
    return self.sync_and_copy_without_lock(project, private_data_dir, scm_branch=scm_branch)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 731, in sync_and_copy_without_lock
    sync_task.run(local_project_sync.id)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 90, in _wrapped
    return f(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/signals.py", line 66, in _wrapped
    return f(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 649, in run
    raise AwxTaskError.TaskError(self.instance, rc)
Exception: project_update 6 (failed) encountered an error (rc=None), please see task stdout for details.
```

Is there any way to increase the log level? 

### AWX Operator version

1.1.0

### AWX version

21.9.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.22

### Modifications

no

### Steps to reproduce

I deployed the Operator according to the "basic install" section and login and start the sample job.

### Expected results

a pod is started in my namespace

### Actual results

no pods are started

### Additional information

i checked the serviceaccounts and they have the corresponding rights to start pods.

**Comment by henrysachs** [comment]
Sorry the issue was network related I found the jobs logs and saw that we can't reach github
