### ISSUE TITLE
This job is not ready to start because there is not enough available capacity

### ISSUE THREAD

**Issue by yogendramummaneni** [ansible/tower-operator#1366]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Installed the latest version of awx using helm
$ helm list  -n awx
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
my-awx-operator awx             1               2023-04-17 15:12:04.515365179 +0000 UTC deployed        awx-operator-2.0.0      2.0.0

Trying to sync dynamic inventory from vCenter source and the job is in pending state for ever.

I can see the following message in job logs from UI.
This job is not ready to start because there is not enough available capacity.

Currently there are no other jobs running. Could you please help in troubleshooting the issue?

### AWX Operator version

2.0.0

### AWX version

2.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.26.3

### Modifications

no

### Steps to reproduce

helm repo add awx-operator https://ansible.github.io/awx-operator/
helm repo update
kubectl create namespace awx
kubectl apply -f admin_password_secret.yaml
helm install -name my-awx-operator -n awx --version=2.0.0 awx-operator/awx-operator -f awx.yaml

Create an dynamic inventory and sync from vcenter source.

### Expected results

Inventory should be synced from vCenter.

### Actual results

![image](https://user-images.githubusercontent.com/8983061/232601970-cb4bfdca-15a3-4e6c-8faa-1dec2818f034.png)

**Comment by fosterseth** [comment]
can you please provide the awx spec, particular limits/requests on the various resources in that file?

can you also provide /api/v2/ping output?

**Comment by fosterseth** [comment]
@yogendramummaneni closing due to inactivity, please feel free to open a new issue if needed

**Comment by telderfts** [comment]
@fosterseth  I'm also having this issue. api/v2/ping is below..

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx-fts-web-9668d7855-b6g4x
X-API-Product-Name: AWX
X-API-Product-Version: 22.3.0
X-API-Time: 0.025s

{
    "ha": false,
    "version": "22.3.0",
    "active_node": "awx-fts-web-9668d7855-b6g4x",
    "install_uuid": "70e9690d-be07-4210-a662-bfa1c7525c4b",
    "instances": [
        {
            "node": "awx-fts-task-5884488b5-28xbq",
            "node_type": "control",
            "uuid": "5e0ebab3-b883-4534-a798-598c91ac9faf",
            "heartbeat": "2023-06-13T16:55:10.283677Z",
            "capacity": 64,
            "version": "22.3.0"
        }
    ],
    "instance_groups": [
        {
            "name": "controlplane",
            "capacity": 64,
            "instances": [
                "awx-fts-task-5884488b5-28xbq"
            ]
        },
        {
            "name": "default",
            "capacity": 0,
            "instances": []
        }
    ]
}

**Comment by KKulishov** [comment]
me too
GET /api/v2/ping/

```
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx-web-54bf5f59fd-nrnwr
X-API-Product-Name: AWX
X-API-Product-Version: 22.3.0
X-API-Time: 0.005s

{
    "ha": false,
    "version": "22.3.0",
    "active_node": "awx-web-54bf5f59fd-nrnwr",
    "install_uuid": "907580a1-dc19-4cfd-9113-671b52a784e0",
    "instances": [
        {
            "node": "awx-task-79df656957-bbw2n",
            "node_type": "control",
            "uuid": "a14416cb-e7da-438f-8dab-222bf7044b24",
            "heartbeat": "2023-06-14T08:28:06.727161Z",
            "capacity": 38,
            "version": "22.3.0"
        }
    ],
    "instance_groups": [
        {
            "name": "controlplane",
            "capacity": 38,
            "instances": [
                "awx-task-79df656957-bbw2n"
            ]
        },
        {
            "name": "default",
            "capacity": 0,
            "instances": []
        },
        {
            "name": "test",
            "capacity": 0,
            "instances": []
        }
    ]
}

```

**Comment by shanemcd** [comment]
There is a bug / UX problem where we allow users to select to run jobs on the `controlplane` instance group. Normal jobs cannot run there and you will see this message. Please verify that you have not selected the `controlplane` IG on your Job Template, Organization, or Inventory.

**Comment by telderfts** [comment]
@shanemcd Then what does one have to do to execute jobs on AWX? All of your tutorials and walkthroughs set this up as an "out of the box" kind of solution so is there something else within AWX that we should be choosing? Do we need to setup seperate execution instances?

**Comment by shanemcd** [comment]
By default it will use `default`, which in Kubernetes-based installs is a Container Group that launches jobs into the namespace in which AWX is deployed.

**Comment by dsupru** [comment]
We are experiencing the same issue.
We deployed AWX via Helm on K3S. Standard installation.

@shanemcd, Is a way to avoid connection leaks (I assume that's what it is) to manually select AWX EE Execution Environment for a Project/Template ?
Removing a task pod helped but we do not want to keep doing that

We have a project with Git source that fails to sync with the error log:
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 1394, in get_connection
    raise ConnectionError("Connection has data")
redis.exceptions.ConnectionError: Connection has data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 604, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 317, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 392, in _run_internal
    res = processor_future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/common.py", line 1188, in wrapper_cleanup_new_process
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 460, in processor
    return ansible_runner.interface.run(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/interface.py", line 211, in run
    r.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/streaming.py", line 355, in run
    self.event_callback(data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/ansible_runner/streaming.py", line 310, in event_callback
    should_write = self.event_handler(event_data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/callback.py", line 222, in event_handler
    super_return_value = super(RunnerCallbackForProjectUpdate, self).event_handler(event_data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/callback.py", line 166, in event_handler
    self.dispatcher.dispatch(event_data)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/queue.py", line 32, in dispatch
    self.connection.rpush(self.queue, json.dumps(obj, cls=AnsibleJSONEncoder))
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/commands/core.py", line 2695, in rpush
    return self.execute_command("RPUSH", name, *values)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/redis/connection.py", line 1399, in get_connection
    raise ConnectionError("Connection not ready")
redis.exceptions.ConnectionError: Connection not ready
```

**Comment by dsupru** [comment]
Same issue again.
@telderfts , can you please share what you ended up doing ?
Manually assigning all templates to "AWX EE Execution Environment" did not help me

**Comment by yoonmin1030** [comment]
Same issue here. 
When I select "default" on "Instance Groups", a Job is run. Is it designed ?? So, every time, I run a job, I have to select "default" on Instance Group?
