### ISSUE TITLE
awx-rsyslog environmental variable

### ISSUE THREAD

**Issue by ubajze** [ansible/tower-operator#1409]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Our AWX deployment uses HashiCorp Vault for database credentials. As there is no way to tell to AWX operator to use Vault for DB creds, we create "dummy" DB creds (`postgres-configuration`). This generates the `/etc/tower/conf.d/credentials.py` file similar to this:

```
bash-5.1$ cat /etc/tower/conf.d/credentials.py
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx",
        'USER': "dummy",
        'PASSWORD': "dummy",
        'HOST': 'dummyhost',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
        },
    }
}
```

Then we use HashiCorp Vault to mount the actual DB settings to `/vault/secrets/database.py`.

```bash-5.1$ cat /vault/secrets/database.py

DATABASES = {
  'default': {
    'ATOMIC_REQUESTS': True,
    'ENGINE': 'awx.main.db.profiled_pg',
    'NAME': '<ACTUAL DB NAME>',
    'USER': '<ACTUAL DB USER>',
    'PASSWORD': '<ACTUAL DB PASSWORD>',
    'HOST': '<ACTUAL DB HOST>',
    'PORT': '5432',
    'OPTIONS': { 'sslmode': 'prefer',
                 'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
    },
  }
}
```

AWX has an environmental variable `AWX_SETTINGS_DIR`, which you can use to specify where to read for django settings. This worked fine in awx-operator pre-2.0. So we set this variable to `AWX_SETTINGS_DIR=/vault/secrets/`.=

In awx-operator 2.x, there is an extra container called `awx-rsyslog`. So, the environmental variable is added to task and web containers but not to rsyslog. So, the task and web containers read DB creds correctly, but the rsyslog container does not, and reads the default DB settings. The rsyslog container executes the script `wait-for-migrations` and because it reads DB creds from the default location the script is stuck and the pods is restarted every ~5-10 minutes.

 If I go to the shell and manually set the environmental variable, commands work fine:
```
bash-5.1$ awx-manage check
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "dummyhost" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 184, in manage
    if (connection.pg_version // 10000) < 12:
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
    with self.temporary_connection():
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
    with self.cursor() as cursor:
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "dummyhost" to address: Name or service not known

bash-5.1$ export AWX_SETTINGS_DIR=/vault/secrets/
bash-5.1$ awx-manage check
System check identified no issues (1 silenced).
bash-5.1$
```

My request is to either apply the same environmental variables (as in the task and web containers) or add another option to specify environmental variables for just for rsyslog.

Another option would be to add an option to prevent generating database settings. Then I can just mount a simple python code, which can load DB (and other) settings from any location on the file-system. Something like this:

```
# file: /vault/secrets/db
# awx_database_foobar,awx_user_foobar,awx_password_foobar

with open('/vault/secrets/db`) as f:
  creds = f.read().split(',')

DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': creds[0],
        'USER': creds[1],
        'PASSWORD': creds[2],
        'HOST': 'dummyhost',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
        },
    }
}
```

I would actually prefer the last option as it gives user the most flexibility.

**Comment by rooftopcellist** [comment]
@ubajze env var configuration on the rsyslog container was overlooked during the web-task split, that should be added regardless.  I have done so in the following PR:
* https://github.com/ansible/awx-operator/pull/1423

That should make it possible to configure these db settings how you were doing, if I understand correctly.  

I'll have to give more thought to conditionally disabling the logic that reads in the postgres_configuration_secret values... I'm hesitant to add more parameters to the CRD, it is already pretty long.

**Comment by ubajze** [comment]
@rooftopcellist thank you for the feedback. I am looking forward to see the PR merged and a new version is released, because we have problems with resets in prod... 

Do you want me to open a new "feature" request for the DB stuff?

**Comment by laiminhtrung1997** [comment]
Dear @rooftopcellist 
CC @ubajze 
Can you add one more option to have rsyslog sidecar container used in both task and web deployment?
Because in my system, I don't use rsyslog. Is this possible for disable rsyslog in AWX?

**Comment by rooftopcellist** [comment]
@ubajze I just merged your PR, thanks for putting that together!  

@laiminhtrung1997 Unfortunately, I don't think that having rsyslog as an optional container will work with the AWX code as it stands today.  There is logic to reconfigure the rsyslog conf file in the case that a new log aggregator is defined in AWX (via the UI or API).  When that happens, it will reach out and edit the rsyslog.conf file and restart rsyslog.  If rsyslog doesn't exist, I am pretty sure it would error.  Maybe there are AWX changes that would enable that to be possible, if so, the best thing to do would be to open an inssue in ansible/awx and see what folks there think.  

For now, I think the best approach would be to set low rsyslog_resource_requirements.requests, that way you use the least possible resources since you don't have an external logger configured.
