### ISSUE TITLE
AWX 22.5 upgrade on 2 K8S cluster, 'WebSocketRelayManager.cleanup_offline_host' fails

### ISSUE THREAD

**Issue by ceteix777** [ansible/tower-operator#1497]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

We have an AWX with  2 cluster K8S configuration (common external postgress db), with container instances as execution envs.
When we fire up only 1 cluster, all works fine.
When we bring up the second cluster, the “awx.main.wsrelay” will try to connect from pods in cluster1 to pods on cluster2 (and the other way around). 
Because it can’t find the other pods coroutine 'WebSocketRelayManager.cleanup_offline_host' fails, and it’s marking its own pod as failing.
In the end, all TASK pods are restarted until Backoff.

Can we isolate somehow the Websocket relay system for “Heartbeet” & “Wsrelay”, and group the pods per cluster? 
Or this behaviour is a bug? (https://github.com/ansible/awx/blob/devel/docs/websockets.md)

### AWX Operator version

2.4

### AWX version

22.5.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.23.14

### Modifications

no

### Steps to reproduce

Create 2 AWX instances (in 2 different K8Sclusters / or 2 different namespaces) sharing the same postgress external database. (AWX HA)
When you start the second cluster, the awx-task container will start fail with the logs below 

### Expected results

we had the same installation on AWX 21.5, which was working using this setup.

### Actual results

We can't run the second instance because the awx-task containers are failing.

### Additional information

awx-test2-task 2023-07-20 10:34:45,625 INFO success: superwatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                    
│ awx-test2-task 2023-07-20 10:34:45,625 INFO success: superwatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                    
│ awx-test2-task 2023-07-20 10:34:46,739 INFO     [-] awx.main.commands.run_callback_receiver Callback receiver started with pid=50                                  
│ awx-test2-task 2023-07-20 10:34:46,764 INFO     [-] awx.main.wsrelay Active instance with hostname awx-test2-task-584bdc44f5-7bsn8 is registered.                  
│ awx-test2-task 2023-07-20 10:34:46,807 WARNING  [-] awx.main.dispatch.periodic periodic beat started                                                               
│ awx-test2-task 2023-07-20 10:34:46,832 INFO     [-] awx.main.dispatch Running worker dispatcher listening to queues ['tower_broadcast_all', 'tower_settings_change', 'awx-test2-task-584bdc44f5-7bsn8'] │
│ awx-test2-task 2023-07-20 10:34:56,776 INFO     [-] awx.main.wsrelay Adding {'awx-test2-web-6c6857cdd7-tzscp', 'awx-test2-web-6c6857cdd7-xqw29', 'awx-test1-web-68bf849ffc-29wzn', 'awx-test1-web-68bf8 │
│ awx-test2-task 2023-07-20 10:34:56,794 INFO     [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.213 established.                
│ awx-test2-task 2023-07-20 10:34:56,795 INFO     [-] awx.main.wsrelay Starting producer for metrics                                                                 
│ awx-test2-task 2023-07-20 10:34:56,798 INFO     [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.214 established.                
│ awx-test2-task 2023-07-20 10:34:56,798 INFO     [-] awx.main.wsrelay Starting producer for metrics                                                                 
│ awx-test2-task 2023-07-20 10:35:06,780 INFO     [-] awx.main.wsrelay Removing {'awx-test1-web-68bf849ffc-29wzn', 'awx-test1-web-68bf849ffc-zx8sf'} from websocket broadcast list                        │
│ awx-test2-task /usr/lib64/python3.9/asyncio/events.py:80: RuntimeWarning: coroutine 'WebSocketRelayManager.cleanup_offline_host' was never awaited                 
│ awx-test2-task   self._context.run(self._callback, *self._args)                                                                                                    
│ awx-test2-task RuntimeWarning: Enable tracemalloc to get the object allocation traceback                                                                           
│ awx-test2-task 2023-07-20 10:35:06,789 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 172.25.157.198 cancelled.    ->> Cluster1              
│ awx-test2-task 2023-07-20 10:35:06,790 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 172.25.157.196 cancelled.    ->> Cluster1              
│ awx-test2-task 2023-07-20 10:35:06,791 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.214 cancelled.    ->> Cluster2              
│ awx-test2-task 2023-07-20 10:35:06,793 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.213 cancelled.    ->> Cluster2
awx-test2-task Traceback (most recent call last):                                                                                                                  
│ awx-test2-task   File "/usr/bin/awx-manage", line 8, in <module>                                                                                                   
│ awx-test2-task     sys.exit(manage())                                                                                                                              
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 200, in manage                                                   
│ awx-test2-task     execute_from_command_line(sys.argv)                                                                                                             
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line             
│ awx-test2-task     utility.execute()                                                                                                                               
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute                               
│ awx-test2-task     self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                         
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv                             
│ awx-test2-task     self.execute(*args, **cmd_options)                                                                                                              
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute                                   
│ awx-test2-task     output = self.handle(*args, **options)                                                                                                          
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_wsrelay.py", line 168, in handle                       
│ awx-test2-task     asyncio.run(websocket_relay_manager.run())                                                                                                      
│ awx-test2-task   File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run                                                                                   
│ awx-test2-task     return loop.run_until_complete(main)                                                                                                            
│ awx-test2-task   File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete                                                               
│ awx-test2-task     return future.result()                                                                                                                          
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/wsrelay.py", line 330, in run                                                  
│ awx-test2-task     await asyncio.gather(self.cleanup_offline_host(h) for h in deleted_remote_hosts)                                                                
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/wsrelay.py", line 330, in <genexpr>                                            
│ awx-test2-task     await asyncio.gather(self.cleanup_offline_host(h) for h in deleted_remote_hosts)                                                                
│ awx-test2-task RuntimeError: Task got bad yield: <coroutine object WebSocketRelayManager.cleanup_offline_host at 0x7fefdc8cce40>                                   
│ awx-test2-task 2023-07-20 10:35:08,314 WARN exited: wsrelay (exit status 1; not expected)                                                                          
│ awx-test2-task 2023-07-20 10:35:08,314 WARN exited: wsrelay (exit status 1; not expected)                                                                          
│ awx-test2-task 2023-07-20 10:35:09,317 INFO spawned: 'wsrelay' with pid 133                                                                                        
│ awx-test2-task 2023-07-20 10:35:09,317 INFO spawned: 'wsrelay' with pid 133                                                                                        
│ awx-test2-task 2023-07-20 10:35:11,359 INFO     [-] awx.main.wsrelay Active instance with hostname awx-test2-task-584bdc44f5-7bsn8 is registered.

Repeats N times,
and then: removed self from capacit

2023-07-20 11:00:48,825 INFO gave up: wsrelay entered FATAL state, too many start retries too quickly                                                                                    │
│ awx-test2-task Processing Event: ver:3.0 server:supervisor serial:0 pool:superwatcher poolserial:0 eventname:PROCESS_STATE_FATAL len:64                                                                 │
│ awx-test2-task 2023-07-20 11:00:49,827 WARN received SIGQUIT indicating exit request                                                                                                                    │
│ awx-test2-task 2023-07-20 11:00:49,827 WARN received SIGQUIT indicating exit request                                                                                                                    │
│ awx-test2-task 2023-07-20 11:00:49,827 INFO waiting for superwatcher, dispatcher, callback-receiver to die                                                                                              │
│ awx-test2-task 2023-07-20 11:00:49,827 INFO waiting for superwatcher, dispatcher, callback-receiver to die                                                                                              │
│ awx-test2-task 2023-07-20 11:00:49,829 WARNING  [24ff42c8c9c64921a6097197bec680a3] awx.main.dispatch received SIGTERM, stopping                                                                         │
│ awx-test2-task 2023-07-20 11:00:49,828 WARNING  [-] awx.main.commands.run_callback_receiver received SIGTERM, stopping                                                                                  │
│ awx-test2-task 2023-07-20 11:00:49,893 WARNING  [24ff42c8c9c64921a6097197bec680a3] awx.main.tasks.system Normal shutdown signal for instance awx-test2-task-584bdc44f5-qfs4d, removed self from capacit │
│ awx-test2-task 2023-07-20 11:00:50,432 INFO stopped: dispatcher (exit status 0)  

### Operator Logs

awx-test2-task 2023-07-20 10:34:45,625 INFO success: superwatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                    
│ awx-test2-task 2023-07-20 10:34:45,625 INFO success: superwatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                    
│ awx-test2-task 2023-07-20 10:34:46,739 INFO     [-] awx.main.commands.run_callback_receiver Callback receiver started with pid=50                                  
│ awx-test2-task 2023-07-20 10:34:46,764 INFO     [-] awx.main.wsrelay Active instance with hostname awx-test2-task-584bdc44f5-7bsn8 is registered.                  
│ awx-test2-task 2023-07-20 10:34:46,807 WARNING  [-] awx.main.dispatch.periodic periodic beat started                                                               
│ awx-test2-task 2023-07-20 10:34:46,832 INFO     [-] awx.main.dispatch Running worker dispatcher listening to queues ['tower_broadcast_all', 'tower_settings_change', 'awx-test2-task-584bdc44f5-7bsn8'] │
│ awx-test2-task 2023-07-20 10:34:56,776 INFO     [-] awx.main.wsrelay Adding {'awx-test2-web-6c6857cdd7-tzscp', 'awx-test2-web-6c6857cdd7-xqw29', 'awx-test1-web-68bf849ffc-29wzn', 'awx-test1-web-68bf8 │
│ awx-test2-task 2023-07-20 10:34:56,794 INFO     [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.213 established.                
│ awx-test2-task 2023-07-20 10:34:56,795 INFO     [-] awx.main.wsrelay Starting producer for metrics                                                                 
│ awx-test2-task 2023-07-20 10:34:56,798 INFO     [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.214 established.                
│ awx-test2-task 2023-07-20 10:34:56,798 INFO     [-] awx.main.wsrelay Starting producer for metrics                                                                 
│ awx-test2-task 2023-07-20 10:35:06,780 INFO     [-] awx.main.wsrelay Removing {'awx-test1-web-68bf849ffc-29wzn', 'awx-test1-web-68bf849ffc-zx8sf'} from websocket broadcast list                        │
│ awx-test2-task /usr/lib64/python3.9/asyncio/events.py:80: RuntimeWarning: coroutine 'WebSocketRelayManager.cleanup_offline_host' was never awaited                 
│ awx-test2-task   self._context.run(self._callback, *self._args)                                                                                                    
│ awx-test2-task RuntimeWarning: Enable tracemalloc to get the object allocation traceback                                                                           
│ awx-test2-task 2023-07-20 10:35:06,789 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 172.25.157.198 cancelled.    ->> Cluster1              
│ awx-test2-task 2023-07-20 10:35:06,790 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 172.25.157.196 cancelled.    ->> Cluster1              
│ awx-test2-task 2023-07-20 10:35:06,791 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.214 cancelled.    ->> Cluster2              
│ awx-test2-task 2023-07-20 10:35:06,793 WARNING  [-] awx.main.wsrelay Connection from awx-test2-task-584bdc44f5-7bsn8 to 198.18.157.213 cancelled.    ->> Cluster2
awx-test2-task Traceback (most recent call last):                                                                                                                  
│ awx-test2-task   File "/usr/bin/awx-manage", line 8, in <module>                                                                                                   
│ awx-test2-task     sys.exit(manage())                                                                                                                              
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 200, in manage                                                   
│ awx-test2-task     execute_from_command_line(sys.argv)                                                                                                             
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line             
│ awx-test2-task     utility.execute()                                                                                                                               
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute                               
│ awx-test2-task     self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                         
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv                             
│ awx-test2-task     self.execute(*args, **cmd_options)                                                                                                              
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute                                   
│ awx-test2-task     output = self.handle(*args, **options)                                                                                                          
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_wsrelay.py", line 168, in handle                       
│ awx-test2-task     asyncio.run(websocket_relay_manager.run())                                                                                                      
│ awx-test2-task   File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run                                                                                   
│ awx-test2-task     return loop.run_until_complete(main)                                                                                                            
│ awx-test2-task   File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete                                                               
│ awx-test2-task     return future.result()                                                                                                                          
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/wsrelay.py", line 330, in run                                                  
│ awx-test2-task     await asyncio.gather(self.cleanup_offline_host(h) for h in deleted_remote_hosts)                                                                
│ awx-test2-task   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/wsrelay.py", line 330, in <genexpr>                                            
│ awx-test2-task     await asyncio.gather(self.cleanup_offline_host(h) for h in deleted_remote_hosts)                                                                
│ awx-test2-task RuntimeError: Task got bad yield: <coroutine object WebSocketRelayManager.cleanup_offline_host at 0x7fefdc8cce40>                                   
│ awx-test2-task 2023-07-20 10:35:08,314 WARN exited: wsrelay (exit status 1; not expected)                                                                          
│ awx-test2-task 2023-07-20 10:35:08,314 WARN exited: wsrelay (exit status 1; not expected)                                                                          
│ awx-test2-task 2023-07-20 10:35:09,317 INFO spawned: 'wsrelay' with pid 133                                                                                        
│ awx-test2-task 2023-07-20 10:35:09,317 INFO spawned: 'wsrelay' with pid 133                                                                                        
│ awx-test2-task 2023-07-20 10:35:11,359 INFO     [-] awx.main.wsrelay Active instance with hostname awx-test2-task-584bdc44f5-7bsn8 is registered.

Repeats N times,
and then: removed self from capacit

2023-07-20 11:00:48,825 INFO gave up: wsrelay entered FATAL state, too many start retries too quickly                                                                                    │
│ awx-test2-task Processing Event: ver:3.0 server:supervisor serial:0 pool:superwatcher poolserial:0 eventname:PROCESS_STATE_FATAL len:64                                                                 │
│ awx-test2-task 2023-07-20 11:00:49,827 WARN received SIGQUIT indicating exit request                                                                                                                    │
│ awx-test2-task 2023-07-20 11:00:49,827 WARN received SIGQUIT indicating exit request                                                                                                                    │
│ awx-test2-task 2023-07-20 11:00:49,827 INFO waiting for superwatcher, dispatcher, callback-receiver to die                                                                                              │
│ awx-test2-task 2023-07-20 11:00:49,827 INFO waiting for superwatcher, dispatcher, callback-receiver to die                                                                                              │
│ awx-test2-task 2023-07-20 11:00:49,829 WARNING  [24ff42c8c9c64921a6097197bec680a3] awx.main.dispatch received SIGTERM, stopping                                                                         │
│ awx-test2-task 2023-07-20 11:00:49,828 WARNING  [-] awx.main.commands.run_callback_receiver received SIGTERM, stopping                                                                                  │
│ awx-test2-task 2023-07-20 11:00:49,893 WARNING  [24ff42c8c9c64921a6097197bec680a3] awx.main.tasks.system Normal shutdown signal for instance awx-test2-task-584bdc44f5-qfs4d, removed self from capacit │
│ awx-test2-task 2023-07-20 11:00:50,432 INFO stopped: dispatcher (exit status 0)

**Comment by fosterseth** [comment]
> Create 2 AWX instances (in 2 different K8Sclusters / or 2 different namespaces) sharing the same postgress external database. (AWX HA)

we don't support multiple AWX instances connecting the same postgres DB

do you see these same errors if you use only on AWX instance per pg instance?

**Comment by ceteix777** [comment]
With 1 deployment all is working fine.
 
With the websocket broadcast system, (before the upgrade) that setup worked for our case of having a GEO-Redundancy cluster, an instance span across 2 K8S clusters with + Container instances.  
https://github.com/ansible/awx/blob/devel/docs/websockets.md

The clustering architecture doc (multi-node / multi control plane) indicates that it is possible to have 2 nodes on the same DB.. otherwise, it is a bit misleading?  
In the end, we need only 2 control nodes that share the same DB, just like in the picture(doc) 
https://github.com/ansible/awx/blob/devel/docs/clustering.md

Do you recommend any different setup for the use-case of a GEO-red setup? 
I think with a bit of heartbeat filtering based on namespace, the use-case can also be made available for others to use.

Best regards

**Comment by john-westcott-iv** [comment]
The linked document to the clustiner.md file is talking about scaling out a single cluster across multiple geo-located nodes, not having multiple clusters with the same DB for GEO-Redundancy. There are other issues we know of that can crop up if your AWX instance and database are not geo-located with near 0 latency (such as the pg notifications in the job task subsystem). We are intrigued with the error `RuntimeError: Task got bad yield` as we recently did some work around async calls in wsrealy and would be interested in figuring out what is causing this specific issue. Unfortunately, at this time, we currently don't have the bandwith to accomplish this in the near term. If you are able to investigate and provide a patch it would be welcome.

**Comment by ceteix777** [comment]
Scaling out one single cluster across geo would work for us, but yet is not clear how to do that with the awx-operator & k8s. Extra docs or suggestions would help.   
Regarding the Runtimeerror, we can make investigate and trace down the issue. (do you recommend any special config to get extra info from the logs?)

**Comment by Amrish-Sharma** [comment]
We are facing this with 2 k8s cluster of AWX with their separate internal postgres pods

**Comment by JSN-1** [comment]
I had the same issue, solved it by deleting awx-task pod, after this awx-task is reinstalled via various playbooks and the problem is gone.

```
kubectl delete pod -n awx awx-task-XXX
```
