### ISSUE TITLE
Tech preview of the new AWX user interface is not getting displayed

### ISSUE THREAD

**Issue by maxbirkner** [ansible/tower-operator#1525]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Instead of the tech preview a page "Server error: A server error has occured" is displayed.

In the logs of the awx-web pod I see the following error message:

```
2023-08-17 07:56:42,105 ERROR    [76afd652baae4eeaa7a5b1cad2412740] django.request Internal Server Error: /ui_next/dashboard                                                                                                   │
│ Traceback (most recent call last):                                                                                                                                                                                             │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner                                                                                                              │
│     response = get_response(request)                                                                                                                                                                                           │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response                                                                                                          │
│     response = response.render()                                                                                                                                                                                               │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 114, in render                                                                                                                  │
│     self.content = self.rendered_content                                                                                                                                                                                       │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 90, in rendered_content                                                                                                         │
│     template = self.resolve_template(self.template_name)                                                                                                                                                                       │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 72, in resolve_template                                                                                                         │
│     return select_template(template, using=self.using)                                                                                                                                                                         │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/loader.py", line 47, in select_template                                                                                                            │
│     raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)                                                                                                                                                     │
│ django.template.exceptions.TemplateDoesNotExist: index_awx.html                                                                                                                                                                │
│ 2023-08-17 07:56:42,105 ERROR    [76afd652baae4eeaa7a5b1cad2412740] django.request Internal Server Error: /ui_next/dashboard                                                                                                   │
│ Traceback (most recent call last):                                                                                                                                                                                             │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner                                                                                                              │
│     response = get_response(request)                                                                                                                                                                                           │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response                                                                                                          │
│     response = response.render()                                                                                                                                                                                               │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 114, in render                                                                                                                  │
│     self.content = self.rendered_content                                                                                                                                                                                       │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 90, in rendered_content                                                                                                         │
│     template = self.resolve_template(self.template_name)                                                                                                                                                                       │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 72, in resolve_template                                                                                                         │
│     return select_template(template, using=self.using)                                                                                                                                                                         │
│   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/loader.py", line 47, in select_template                                                                                                            │
│     raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)                                                                                                                                                     │
│ django.template.exceptions.TemplateDoesNotExist: index_awx.html                                                                                                                                                                │
│ 10.244.3.218 - - [17/Aug/2023:07:56:42 +0000] "GET /ui_next/dashboard HTTP/1.1" 500 3887 "https://awx.dev.internal.redacted/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Sa │
│ [pid: 134|app: 0|req: 34/167] 10.244.3.218 () {76 vars in 2463 bytes} [Thu Aug 17 07:56:41 2023] GET /ui_next/dashboard => generated 3887 bytes in 110 msecs (HTTP/1.1 500) 9 headers in 390 bytes (1 switches on core 0)
```

### AWX Operator version

2.5.1

### AWX version

22.7.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.25.5

### Modifications

no

### Steps to reproduce

Open AWX dashboard, click link in banner `A tech preview of the new AWX user interface can be found [here](https://awx.dev.internal.fernride.tech/ui_next/dashboard).`

### Expected results

See tech preview.

### Actual results

Received error message -> see bug summary

**Comment by kurokobo** [comment]
Refer to: https://github.com/ansible/awx/issues/14345

**Comment by TheRealHaoLiu** [comment]
Thanks for reporting, closing this issue. Fixed provided in https://github.com/ansible/awx/issues/14345
