### ISSUE TITLE
Starting a new Job fails - unrecognized configuration parameter "idle_session_timeout"

### ISSUE THREAD

**Issue by brigzzy** [ansible/tower-operator#1915]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Howdy folks!  Big fan of AWX, super grateful to everyone that helps make it happen :) 

I'm having some issues since upgrading from 2.14.0 to 2.19.1.  The upgrade seemed to complete successfully, but I'm not able to start jobs.  In the web UI, they stay stuck on Pending.  

### AWX Operator version

2.19.1

### AWX version

24.6.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.28.10 +rke2r1

### Modifications

no

### Steps to reproduce

- Install AWX Operator 2.16.0
- Upgrade the operator to 2.19.1

### Expected results

Jobs continue to run

### Actual results

Jobs fail to run.  The logs in the task container show the following repeating message:

```
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1
min_value in DecimalField should be Decimal type.
Instance Group already registered controlplane
Instance Group already registered default
Successfully registered instance None
(changed: True)
2024-07-07 22:48:54,894 INFO RPC interface 'supervisor' initialized
2024-07-07 22:48:54,894 INFO RPC interface 'supervisor' initialized
2024-07-07 22:48:54,895 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-07-07 22:48:54,895 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-07-07 22:48:54,895 INFO supervisord started with pid 8
2024-07-07 22:48:54,895 INFO supervisord started with pid 8
2024-07-07 22:48:55,899 INFO spawned: 'superwatcher' with pid 38
2024-07-07 22:48:55,899 INFO spawned: 'superwatcher' with pid 38
2024-07-07 22:48:55,905 INFO spawned: 'dispatcher' with pid 39
2024-07-07 22:48:55,905 INFO spawned: 'dispatcher' with pid 39
2024-07-07 22:48:55,910 INFO spawned: 'callback-receiver' with pid 40
2024-07-07 22:48:55,910 INFO spawned: 'callback-receiver' with pid 40
2024-07-07 22:48:55,917 INFO spawned: 'wsrelay' with pid 41
2024-07-07 22:48:55,917 INFO spawned: 'wsrelay' with pid 41
READY
2024-07-07 22:48:56,928 INFO success: superwatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-07 22:48:56,928 INFO success: superwatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-07 22:48:56,929 INFO success: wsrelay entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-07 22:48:56,929 INFO success: wsrelay entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-07 22:49:03,709 INFO     [-] awx.main.commands.run_callback_receiver Callback receiver started with pid=40
2024-07-07 22:49:03,761 INFO     [-] awx.main.dispatch Running worker dispatcher listening to queues ['tower_broadcast_all', 'tower_settings_change', 'awx-task-5b85f59777-48x7p']
2024-07-07 22:49:04,027 WARNING  [-] awx.main.tasks.system Rejoining the cluster as instance awx-task-5b85f59777-48x7p. Prior last_seen None
2024-07-07 22:49:04,088 INFO     [-] awx.main.dispatch Dispatcher listener connection established
2024-07-07 22:49:04,088 WARNING  [-] awx.main.dispatch.periodic Scheduler next run unexpectedly over 20 seconds in future: 25.67236328125
2024-07-07 22:49:04,193 INFO     [-] awx.main.wsrelay Active instance with hostname awx-task-5b85f59777-48x7p is registered.
2024-07-07 22:49:04,198 INFO     [-] awx.main.wsrelay Starting Websocket Relayer...
2024-07-07 22:49:14,220 INFO     [-] awx.main.wsrelay Adding {'awx-web-6fdd778479-pzjg5'} to websocket broadcast list
2024-07-07 22:49:14,239 INFO     [-] awx.main.wsrelay Connection from awx-task-5b85f59777-48x7p to 10.42.143.56 established.
2024-07-07 22:49:14,240 INFO     [-] awx.main.wsrelay Starting producer for metrics
2024-07-07 22:49:26,253 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 30 seconds (startsecs)
2024-07-07 22:49:26,253 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 30 seconds (startsecs)
2024-07-07 22:49:26,254 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 30 seconds (startsecs)
2024-07-07 22:49:26,254 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 30 seconds (startsecs)
2024-07-07 22:49:27,256 WARNING  [-] awx.main.wsrelay Producer 10.42.143.56-control-limit_reached_1 not found.
2024-07-07 22:49:27,264 WARNING  [-] awx.main.wsrelay Producer 10.42.143.56-jobs-status_changed not found.
2024-07-07 22:49:27,265 WARNING  [-] awx.main.wsrelay Producer 10.42.143.56-schedules-changed not found.
2024-07-07 22:49:27,433 INFO     [-] awx.main.wsrelay Starting producer for 10.42.143.56-control-limit_reached_1
2024-07-07 22:49:27,436 INFO     [-] awx.main.wsrelay Starting producer for 10.42.143.56-jobs-status_changed
2024-07-07 22:49:29,840 ERROR    [-] awx.main.dispatch Worker failed to run task awx.main.scheduler.tasks.task_manager(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedObject: unrecognized configuration parameter "idle_session_timeout"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/dispatch/worker/task.py", line 103, in perform_work
    result = self.run_callable(body)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/dispatch/worker/task.py", line 78, in run_callable
    return _call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/tasks.py", line 25, in task_manager
    run_manager(TaskManager, "task")
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/tasks.py", line 20, in run_manager
    manager().schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/task_manager.py", line 142, in schedule
    with advisory_lock(f"{self.prefix}_lock", lock_session_timeout_milliseconds=lock_session_timeout_milliseconds, wait=False) as acquired:
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/pglock.py", line 19, in advisory_lock
    idle_session_timeout = cur.execute('SHOW idle_session_timeout').fetchone()[0]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: unrecognized configuration parameter "idle_session_timeout"
```

### Additional information

This looks similar to [this issue](https://github.com/ansible/awx-operator/issues/1501), but not 100%, so I figured a new report made sense.

### Operator Logs

The operator seemed to run successfully, and I don't see any errors in the rest of the logs:

```
PLAY RECAP *********************************************************************
localhost                  : ok=86   changed=0    unreachable=0    failed=0    skipped=87   rescued=0    ignored=1   
```

**Comment by simon-pp** [comment]
What version of Postgresql are you using? We were on 12 and had this issue upgrading to 14 fixed it.

**Comment by brigzzy** [comment]
> What version of Postgresql are you using? We were on 12 and had this issue upgrading to 14 fixed it.

That was the issue!  Thank you!  I was on Postgres 13, and upgraded to 15, and I'm back in business.  

Cheers!
