### ISSUE TITLE
Restore leaves broken awx_task container

### ISSUE THREAD

**Issue by SebastianLeitz** [ansible/tower-operator#1962]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Restoring an AWX backup spins up the web interface, but the task container does not work. It shows a database column error.

### AWX Operator version

2.9.0

### AWX version

23.5.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.20.11

### Modifications

no

### Steps to reproduce

 * Restore a backup of AWX (previously created like described in the [manual](https://github.com/ansible/awx-operator/blob/devel/roles/backup/README.md))
 * Wait until the manager stops spinning up resources and the database has been restored
 * Log in to the web interface
 * Launch any job

### Expected results

The job should start and complete.

### Actual results

The job stays pending for eternity. Inspecting the `awx_task` pod shows the error message:

```
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1
Traceback (most recent call last):
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column "listener_port" of relation "main_instance" does not exist
LINE 1: ...city", "mem_capacity", "node_type", "node_state", "listener_...
```

**Comment by NikBayov** [comment]
I deployed two instances(x,y) of the awx operator in different k8s clusters(1.28,1.32), then I decided to connect db(x) to awx(y) and I noticed that the database schemas were different, db(x) was missing two columns and some values in the main_instance table. I was able to manually fix it with these commands:
```
ALTER TABLE main_instance
ADD COLUMN IF NOT EXISTS peers_from_control_nodes boolean NOT NULL DEFAULT false;
UPDATE main_instance SET managed = false WHERE managed IS NULL;
ALTER TABLE main_instance ALTER COLUMN managed SET DEFAULT false;
ALTER TABLE main_instance ALTER COLUMN managed SET NOT NULL;
ALTER TABLE main_instance ALTER COLUMN peers_from_control_nodes SET DEFAULT false;
UPDATE main_instance
SET peers_from_control_nodes = false
WHERE peers_from_control_nodes IS NULL;
ALTER TABLE main_instance ALTER COLUMN peers_from_control_nodes SET NOT NULL;
ALTER TABLE main_instance ADD COLUMN IF NOT EXISTS listener_port integer;
```
