### ISSUE TITLE
Unable to Import Ansible Inventory into AWX

### ISSUE THREAD

**Issue by psalibindla-rubrik** [ansible/tower-operator#201]
I am unable to import hosts file into awx inventory

**Comment by tchellomello** [comment]
@psalibindla-rubrik could you please elaborate and provide an example of the steps you performed and the error you are hitting?

**Comment by psalibindla-rubrik** [comment]
Below are the steps that I have executed:.

1. I have successfully created a project using Github.
2. When I am trying to import inventory using Sourced from a Project. it failing with below error:
ansible-inventory [core 2.11.0b3.post0] 
  config file = /tmp/pdd_wrapper_40_5jzl17h4/awx_40_tuq_2p_3/project/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
Using /tmp/pdd_wrapper_40_5jzl17h4/awx_40_tuq_2p_3/project/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callback_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Ignoring invalid path provided to plugin path:
'/runner/project/inventories/rbk_cloud_fabric/hosts' is not a directory
host_list declined parsing /runner/project/inventories/rbk_cloud_fabric/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /runner/project/inventories/rbk_cloud_fabric/hosts as it did not pass its verify_file() method
auto declined parsing /runner/project/inventories/rbk_cloud_fabric/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /runner/project/inventories/rbk_cloud_fabric/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user 

I have tried to login to awx-task container and tried to run the below common :
awx-manage inventory_import --source=/var/lib/awx/projects/_8__network_automation/inventories/rbk_cloud_fabric/hosts  --inventory-name="RCF_EVPN_SWITCHES"
    1.604 INFO     Updating inventory 2: RCF_EVPN_SWITCHES
2021-04-09 06:03:39,729 DEBUG    [-] awx.analytics.job_lifecycle inventoryupdate-16 created
    1.704 INFO     Reading Ansible inventory source: /var/lib/awx/projects/_8__network_automation/inventories/rbk_cloud_fabric/hosts
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 898, in handle
    source=source, venv_path=venv_path, verbosity=verbosity
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 148, in load
    return self.command_to_json(base_args)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 123, in command_to_json
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'podman': 'podman'

**Comment by ewebcat** [comment]
I get the same error

bash-4.4$ awx-manage inventory_import --inventory-name winservers --source ./test.yaml 
    0.995 INFO     Updating inventory 2: winservers
2021-04-20 18:04:21,346 DEBUG    [-] awx.analytics.job_lifecycle inventoryupdate-114 created
    1.287 INFO     Reading Ansible inventory source: /var/lib/awx/projects/_8__mygit/test.yaml
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 164, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 872, in handle
    data = AnsibleInventoryLoader(source=source, venv_path=venv_path, verbosity=verbosity).load()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 132, in load
    return self.command_to_json(base_args)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 108, in command_to_json
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'podman'

**Comment by binhvcom** [comment]
i get the same error

~# kubectl exec --stdin --tty awx-b5f6cf4d4-mw4tj --container awx-task -- awx-manage inventory_import --inventory-name master --source /tmp/master --overwrite
    0.957 INFO     Updating inventory 3: master
2021-04-22 07:21:31,988 DEBUG    [-] awx.analytics.job_lifecycle inventoryupdate-58 created
    1.115 INFO     Reading Ansible inventory source: /tmp/master
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 164, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 872, in handle
    data = AnsibleInventoryLoader(source=source, venv_path=venv_path, verbosity=verbosity).load()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 132, in load
    return self.command_to_json(base_args)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/inventory_import.py", line 108, in command_to_json
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'podman'
command terminated with exit code 1

**Comment by ewebcat** [comment]
yaml was not formatted properly. ignoe my post.

**Comment by wenottingham** [comment]
This is https://github.com/ansible/awx/issues/10137, will be tracked there.
