### ISSUE TITLE
AWX cannot launch jobs - no available capacity to run containerized job

### ISSUE THREAD

**Issue by RylandDeGregory** [ansible/tower-operator#236]
Since I've added a new execution environment, I am now unable to launch jobs using any execution environment. I'm not sure why the capacity shows 0...is there a setting I need to configure?

This is the error output from `awx_task`:

```
2021-04-21 21:30:07,289 DEBUG    [a19ebf96248e48fcbd700b06177397a2] awx.main.dispatch task 913b97c9-2dac-47ed-bbf2-1ae0bb17d860 starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-04-21 21:30:07,290 DEBUG    [a19ebf96248e48fcbd700b06177397a2] awx.main.scheduler Running Tower task manager.
2021-04-21 21:30:07,299 DEBUG    [a19ebf96248e48fcbd700b06177397a2] awx.main.scheduler Starting Scheduler
2021-04-21 21:30:07,313 DEBUG    [a19ebf96248e48fcbd700b06177397a2] awx.main.dispatch task a970f911-0ebc-4bee-af94-1a3dd14bd156 starting awx.main.analytics.analytics_tasks.send_subsystem_metrics(*[])
2021-04-21 21:30:07,323 DEBUG    [a19ebf96248e48fcbd700b06177397a2] awx.main.scheduler Finishing Scheduler
2021-04-21 21:30:17,314 DEBUG    [5b4eeef9f56b4101a957800ccc0fe62c] awx.main.dispatch task 1dda4970-b3fa-4d5f-aa0a-4732220f8c5a starting awx.main.tasks.awx_periodic_scheduler(*[])
2021-04-21 21:30:17,325 DEBUG    [5b4eeef9f56b4101a957800ccc0fe62c] awx.main.tasks Starting periodic scheduler
2021-04-21 21:30:17,327 DEBUG    [5b4eeef9f56b4101a957800ccc0fe62c] awx.main.tasks Last scheduler run was: 2021-04-21 21:29:47.297612+00:00
2021-04-21 21:30:27,333 DEBUG    [b9290787257d473fa03276d6e48a233b] awx.main.dispatch task 9da7384a-9844-4819-b431-5cea4f35f494 starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-04-21 21:30:27,335 DEBUG    [b9290787257d473fa03276d6e48a233b] awx.main.scheduler Running Tower task manager.
2021-04-21 21:30:27,343 DEBUG    [b9290787257d473fa03276d6e48a233b] awx.main.scheduler Starting Scheduler
2021-04-21 21:30:27,358 DEBUG    [b9290787257d473fa03276d6e48a233b] awx.main.dispatch task 6f4583a6-9c77-422f-a4c2-10bddd397425 starting awx.main.analytics.analytics_tasks.send_subsystem_metrics(*[])
2021-04-21 21:30:27,367 DEBUG    [b9290787257d473fa03276d6e48a233b] awx.main.scheduler Finishing Scheduler
2021-04-21 21:30:31,227 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.dispatch task c3684623-48d2-42f8-ab78-8478521b29c2 starting awx.main.tasks.update_inventory_computed_fields(*[2])
2021-04-21 21:30:31,241 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.models.inventory Going to update inventory computed fields, pk=2
2021-04-21 21:30:31,266 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.models.inventory Finished updating inventory computed fields, pk=2, in 0.024 seconds
2021-04-21 21:30:31,426 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.dispatch task 4223ed44-e6ba-4865-b5ca-251b6102e765 starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-04-21 21:30:31,428 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler Running Tower task manager.
2021-04-21 21:30:31,436 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler Starting Scheduler
2021-04-21 21:30:31,477 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle job-27 acknowledged
2021-04-21 21:30:31,501 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle projectupdate-28 created
2021-04-21 21:30:31,533 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler Spawned project_update 28 (pending) as dependency of job 27 (pending)
2021-04-21 21:30:31,562 WARNING  [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler No available capacity to run containerized <project_update 28 (waiting)>.
2021-04-21 21:30:31,607 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle projectupdate-28 waiting
2021-04-21 21:30:31,608 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler project_update 28 (waiting) consumed 0 capacity units from tower with prior total of 0
2021-04-21 21:30:31,612 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle job-27 blocked by projectupdate-28
2021-04-21 21:30:31,613 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler Finishing Scheduler
2021-04-21 21:30:31,636 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.dispatch task ba438bdf-7e1b-4fc8-87ae-d1e237257757 starting awx.main.tasks.RunProjectUpdate(*[28])
2021-04-21 21:30:31,727 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle projectupdate-28 pre run
2021-04-21 21:30:31,737 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle projectupdate-28 preparing playbook
2021-04-21 21:30:31,744 WARNING  [7d47c59012664b5f879a143a7cbe446e] awx.main.tasks Galaxy role/collection syncing is enabled, but no credentials are configured for Org-2.
2021-04-21 21:30:31,764 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle projectupdate-28 running playbook
2021-04-21 21:30:32,803 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:32,803 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,048 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,048 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,057 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,057 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,059 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,059 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,802 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,803 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,803 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,802 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,806 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,806 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,809 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:33,809 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:34,049 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(9)
2021-04-21 21:30:34,049 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(9)
2021-04-21 21:30:34,052 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(9)
2021-04-21 21:30:34,052 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(9)
2021-04-21 21:30:34,055 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(6)
2021-04-21 21:30:34,055 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(6)
2021-04-21 21:30:34,058 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:34,058 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2021-04-21 21:30:34,080 INFO     [7d47c59012664b5f879a143a7cbe446e] awx.main.commands.run_callback_receiver Event processing is finished for Job 28, sending notifications
2021-04-21 21:30:34,080 INFO     [7d47c59012664b5f879a143a7cbe446e] awx.main.commands.run_callback_receiver Event processing is finished for Job 28, sending notifications
2021-04-21 21:30:34,112 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.dispatch task da2a3897-8851-4891-99d1-dae989997666 starting awx.main.tasks.handle_success_and_failure_notifications(*[28])
2021-04-21 21:30:34,815 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.tasks project_update 28 (running) finished running, producing 33 events.
2021-04-21 21:30:34,820 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle projectupdate-28 post run
2021-04-21 21:30:34,827 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.tasks project_update 28 (running) wrote to cache at /var/lib/awx/projects/.__awx_cache/_12__test/28
2021-04-21 21:30:34,914 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle projectupdate-28 finalize run
2021-04-21 21:30:34,919 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.dispatch task ba438bdf-7e1b-4fc8-87ae-d1e237257757 starting awx.main.tasks.handle_work_success(*[])
2021-04-21 21:30:34,930 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.dispatch task dff00576-83a2-47b3-91e0-da17ce6c2e0c starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-04-21 21:30:34,931 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler Running Tower task manager.
2021-04-21 21:30:34,938 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler Starting Scheduler
2021-04-21 21:30:34,994 WARNING  [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler No available capacity to run containerized <job 27 (waiting)>.
2021-04-21 21:30:35,023 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle job-27 waiting
2021-04-21 21:30:35,024 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler job 27 (waiting) consumed 2 capacity units from tower with prior total of 0
2021-04-21 21:30:35,024 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.scheduler Finishing Scheduler
2021-04-21 21:30:35,037 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.dispatch task 4cff742d-5407-4f34-8355-a7f0c38eecc5 starting awx.main.tasks.RunJob(*[27])
2021-04-21 21:30:35,180 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.analytics.job_lifecycle job-27 pre run
2021-04-21 21:30:35,187 DEBUG    [7d47c59012664b5f879a143a7cbe446e] awx.main.tasks Skipping project sync for job 27 (running) because commit is locally available
2021-04-21 21:30:35,221 ERROR    [7d47c59012664b5f879a143a7cbe446e] awx.main.tasks job 27 (running) Exception occurred while running task
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1304, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1827, in pre_run_hook
    RunProjectUpdate.make_local_copy(job.project, private_data_dir, scm_revision=job_revision)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2230, in make_local_copy
    source_branch = git_repo.create_head(tmp_branch_name, p.scm_revision)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/repo/base.py", line 386, in create_head
    return Head.create(self, path, commit, force, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/refs/symbolic.py", line 543, in create
    return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/refs/symbolic.py", line 510, in _create
    ref.set_reference(target, logmsg)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/refs/symbolic.py", line 326, in set_reference
    assure_directory_exists(fpath, is_file=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/git/util.py", line 177, in assure_directory_exists
    os.makedirs(path, exist_ok=True)
  File "/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/awx/projects/_12__test/.git/refs/heads/awx_internal'
```
and the same error in AWX web ui: ![Screen Shot 2021-04-21 at 5 34 54 PM](https://user-images.githubusercontent.com/18073815/115623946-e5a63a00-a2c7-11eb-82d9-912ac9d2079c.png)

**Comment by shanemcd** [comment]
Very interesting. It looks like maybe your custom EE ran as root? Will need to think about ways to prevent letting you get into this state to begin with.

As a workaround, do things work with the default EE if you delete your AWX pod and let it recreate?

**Comment by RylandDeGregory** [comment]
It happened because I was following the instructions here https://github.com/ansible/awx/issues/9917, here https://github.com/ansible/ansible-builder/issues/206, and here https://github.com/ansible/ansible-builder/pull/205 to finally get a custom EE up and running that would allow the pod to create. It's been very painful...but adding the `USER root` was the only thing that allowed the custom EE to build. I guess that is causing this problem downstream?

**Comment by daenney** [comment]
I'm stuck on the exact same thing right now. @RylandDeGregory did you manage to work around this somehow?

**Comment by RylandDeGregory** [comment]
@daenney no, I have not. I've basically given up on using a custom EE, as they seem to just not work at all right now even if you can manage to black magic your way to a working ansible-builder image. See: https://github.com/ansible/awx-operator/issues/254#issuecomment-828592473

**Comment by daenney** [comment]
@RylandDeGregory :sob:.

I need a custom EE b/c based on my understanding that's the only way to get collections installed. Does anyone have a way around either the EE issue or getting collections sorted?

**Comment by ilijamt** [comment]
I basically did this. 

```
FROM quay.io/ansible/awx-ee:0.1.1

USER root 

ADD requirements.txt /tmp/requirements.txt
ADD requirements.yml /tmp/requirements.yml

RUN pip install -r /tmp/requirements.txt
RUN ansible-galaxy role install -r /tmp/requirements.yml --roles-path /usr/share/ansible/roles
RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r /tmp/requirements.yml --collections-path /usr/share/ansible/collections

USER 1000
```

```
$ cat requirements.txt 
dnspython
winrm

$ cat requirements.yml 
---
collections:
- community.general
- ansible.windows
```

I gave up on using ansible-builder as it's missing dependencies in the build process. I even tried running a blank environment to just see if it's going to work nope same error.

**Comment by RylandDeGregory** [comment]
@daenney you can use a requirements.txt in the root of your git repository. See: https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file

Additionally, the default EE ships with a lot of Collections pre-installed: https://github.com/ansible/awx-ee/blob/devel/_build/requirements.yml

**Comment by daenney** [comment]
> @daenney you can use a requirements.txt in the root of your git repository. See: https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
> 
> Additionally, the default EE ships with a lot of Collections pre-installed: https://github.com/ansible/awx-ee/blob/devel/_build/requirements.yml

Yeah. Unfortunately community.general and community.aws are missing, both of which I need :disappointed:. I guess I'll resort to bundling it

**Comment by daenney** [comment]
> I basically did this.
> 
> ```
> FROM quay.io/ansible/awx-ee:0.1.1
> 
> USER root 
> 
> ADD requirements.txt /tmp/requirements.txt
> ADD requirements.yml /tmp/requirements.yml
> 
> RUN pip install -r /tmp/requirements.txt
> RUN ansible-galaxy role install -r /tmp/requirements.yml --roles-path /usr/share/ansible/roles
> RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r /tmp/requirements.yml --collections-path /usr/share/ansible/collections
> 
> USER 1000
> ```
> 
> ```
> $ cat requirements.txt 
> dnspython
> winrm
> 
> $ cat requirements.yml 
> ---
> collections:
> - community.general
> - ansible.windows
> ```
> 
> I gave up on using ansible-builder as it's missing dependencies in the build process. I even tried running a blank environment to just see if it's going to work nope same error.

@ilijamt Just for my understanding, did doing that and then using it as an EE work for you? Or did you manage to build it that way but then still get stuck?

**Comment by ilijamt** [comment]
It builds and I can run it but it's not detecting the collections. I
manually logged in the container and the collections and roles are there
but not picked up when the ansible runs, which is weird. Haven't had a
chance to take a deeper look into why it's not being picked up.

**Comment by daenney** [comment]
Your Dockerfile seems to work for me! It also picks up the extra collections I installed that way. Thanks a lot for the help.

W.r.t collections, it might be worth double-checking if you specify `collections_paths` in any `ansible.cfg`, and make sure it includes the `/usr/share/...` path too.

**Comment by ilijamt** [comment]
For me I'm trying to use the collections in the inventory, in the playbook it works but not during a dynamic inventory.

```
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /example.proxmox.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /example.proxmox.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /example.proxmox.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /example.proxmox.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /example.proxmox.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /example.proxmox.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse /example.proxmox.yml as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by fferraro87** [comment]
so @daenney you've solved? because i've also same error
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Pod Running
```

**Comment by daenney** [comment]
@fferraro87 this works well enough for me on 19.0, using this `Dockerfile` to build a custom EE:

```dockerfile
FROM quay.io/ansible/awx-ee:0.1.1

USER root

ADD collections.yml /tmp/collections.yml
ADD requirements.txt /tmp/requirements.txt

RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r /tmp/collections.yml --collections-path /usr/share/ansible/collections
RUN pip install -r /tmp/requirements.txt

USER 1000
```

Ansible 19.1 with EE 0.2.0 as a base however has broken for me in new and exciting ways though I'm not sure if it's related to the EE or something else.

**Comment by wenottingham** [comment]
There was a protocol change that requires syncing EE versions with AWX versions. AWX 19.2 requires awx-ee 0.3.0, and all custom images will need rebased on that.

**Comment by daenney** [comment]
> AWX 19.x requires awx-ee 0.3.0, and all custom images will need rebased on that.

I don't think that's quite correct.

* AWX 19.0 worked with EE 0.1.1
* AWX 19.1 I couldn't get things to work with EE images based on 0.1.x or 0.2.x
* AWX 19.2 is out which mentions needing EE 0.3.x, I'll give that a go

**Comment by wenottingham** [comment]
I've updated the comment. I believe that will fix the issues described here - please reopen if you still see issues once the EE and AWX versions have been synchronized.

**Comment by telderfts** [comment]
@wenottingham Seeing this as well when running the latest version of AWX in K8's. Just running a simple inventory job against AWS and get "awx.analytics.job_lifecycle inventoryupdate-1 needs capacity" even though the pods all have capacity and are running on beefy EC2 instances underlying them.

**Comment by dixittanmay91** [comment]
@wenottingham We are also experiencing the same issue with AWX 21.1.0 which is installed on Kubernetes. Running a simple inventory job is going to Pending status due to capacity issue. We also checked that the pod has the required capacity to run the job.

![image](https://github.com/ansible/awx-operator/assets/10458750/14f6108a-14cd-45b7-9bf5-6182578fe4c9)

**Comment by latheefp** [comment]
Dears, any solution availabel for this issue.

```
2025-07-08 08:32:14,235 INFO     [-] awx.main.wsrelay Starting producer for 10.244.18.26-schedules-changed
2025-07-08 08:32:16,229 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:32:36,225 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:32:56,213 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:33:16,216 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:33:36,224 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:33:56,206 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:34:16,240 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:34:36,228 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:34:56,228 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
2025-07-08 08:35:16,215 INFO     [03c65b91bf6e442f888bf18b4994062e] awx.analytics.job_lifecycle inventoryupdate-7772 needs capacity
```
