### ISSUE TITLE
[ Instance Groups ] Jobs running on custom instance group fail or are in running state forever

### ISSUE THREAD

**Issue by MateuszKuchniak-TomTom** [ansible/tower-operator#254]
Hi,

I am trying to setup custom instance group so that we can use multiple Ansible version as needed per job. I've created instance group with ansible 2.10 image. Running any job on this instance group fails with following error: 

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Pod Running
```
Or the job is in running state forever, without any info in stdout. In both cases the pod with image is scheduled. I've tried many custom pod templates, running on ansible-runner images and awx-ee form quay,io 

my setup:

AWX operator 19
K8S: 1.18.14

All other jobs that are ran on default instance group are working fine. 

Kind Regards

**Comment by RylandDeGregory** [comment]
Getting the same error with a custom EE created using ansible-builder. The official 0.1.1 EE image works fine for me though.

UPDATE:

After doing some testing, if you define anything in the awx spec under `tower_ee_images`, it fails to launch jobs, including if you define the 0.2.0 version of the AWX EE.

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal
    raise RuntimeError(detail)
RuntimeError: exit status 0
```
---

Unrelated, but I've also seen that the "Execution Environment" that you specify on a Template doesn't actually mean anything, and the `job` pods will always launch with the same EE image as the `awx-ee` container running in the `awx` pod.

**Comment by wenottingham** [comment]
Hi -

You have a mismatch between your AWX version and your awx-ee versions. Unfortunately there was some protocol changes. If you are using AWX 19 or later you need awx-ee 0.3.0 or later, and you'll need to rebuild any custom EEs on top of that.
