### ISSUE TITLE
Empty instance group "tower"

### ISSUE THREAD

**Issue by sfhl** [ansible/tower-operator#286]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Instance group "tower" is always empty. Even if the group is "deleted", awx-task will re-create it, but it seems that it will not register itself to this group, instead it appears as ungrouped. Jobs are executed.

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: none
* Kubernetes version: v1.17.9
* AWX install method: custom k8s

##### STEPS TO REPRODUCE
deploy the whole stack

##### EXPECTED RESULTS
instance group is not empty

##### ACTUAL RESULTS
instance group is empty

##### list_instances
```
awx-manage list_instances
[tower capacity=0 policy=100%]

[ungrouped capacity=0]
        awx-task-84878bb898-6fhnh capacity=0 version=19.1.0
```

##### AWX-TASK LOGS
```
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 10
2021-05-06 07:03:31,558 INFO RPC interface 'supervisor' initialized
2021-05-06 07:03:31,558 INFO RPC interface 'supervisor' initialized
2021-05-06 07:03:31,558 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-05-06 07:03:31,558 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-05-06 07:03:31,558 INFO supervisord started with pid 22
2021-05-06 07:03:31,558 INFO supervisord started with pid 22
2021-05-06 07:03:32,560 INFO spawned: 'awx-config-watcher' with pid 25
2021-05-06 07:03:32,560 INFO spawned: 'awx-config-watcher' with pid 25
2021-05-06 07:03:32,563 INFO spawned: 'dispatcher' with pid 26
2021-05-06 07:03:32,563 INFO spawned: 'dispatcher' with pid 26
2021-05-06 07:03:32,565 INFO spawned: 'callback-receiver' with pid 27
2021-05-06 07:03:32,565 INFO spawned: 'callback-receiver' with pid 27
READY
2021-05-06 07:03:33,687 INFO success: awx-config-watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:33,687 INFO success: awx-config-watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:33,687 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:33,687 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:33,688 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:33,688 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:35,082 WARNING  [-] awx.main.dispatch.periodic periodic beat started
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 164, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/run_callback_receiver.py", line 31, in handle
    CallbackBrokerWorker(),
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/worker/callback.py", line 49, in __init__
    self.subsystem_metrics = s_metrics.Metrics(auto_pipe_execute=False)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/analytics/subsystem_metrics.py", line 153, in __init__
    self.instance_name = Instance.objects.me().hostname
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/managers.py", line 107, in me
    raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
2021-05-06 07:03:35,199 INFO     [-] awx.main.dispatch Registered node 'awx-task-84878bb898-6fhnh'
Instance Group already registered tower
(changed: True)
2021-05-06 07:03:35,222 WARNING  [-] awx.main.dispatch scaling up worker pid:35
2021-05-06 07:03:35,234 WARNING  [-] awx.main.dispatch scaling up worker pid:36
2021-05-06 07:03:35,243 WARNING  [-] awx.main.dispatch scaling up worker pid:37
2021-05-06 07:03:35,256 WARNING  [-] awx.main.dispatch scaling up worker pid:38
2021-05-06 07:03:35,262 WARNING  [-] awx.main.dispatch Running worker dispatcher listening to queues ['tower_broadcast_all', 'awx-task-84878bb898-6fhnh']
2021-05-06 07:03:35,295 DEBUG    [-] awx.main.tasks Syncing Schedules
2021-05-06 07:03:35,367 DEBUG    [-] awx.main.tasks Waited 0.0023038387298583984 seconds to obtain lock name: cluster_policy_lock
2021-05-06 07:03:35,379 DEBUG    [-] awx.main.tasks Total instances: 2, available for policy: 2
2021-05-06 07:03:35,380 DEBUG    [-] awx.main.tasks Policy percentage, adding Instances [32, 33] to Group tower
2021-05-06 07:03:35,381 DEBUG    [-] awx.main.tasks Skipping containerized group tower for policy calculation
2021-05-06 07:03:35,382 DEBUG    [-] awx.main.tasks Cluster policy computation finished in 0.013860464096069336 seconds
2021-05-06 07:03:35,384 DEBUG    [-] awx.main.tasks Cluster node heartbeat task.
2021-05-06 07:03:35,481 INFO     [-] awx.main.tasks Host awx-task-bd86849db-vkqht Automatically Deprovisioned.
2021-05-06 07:03:35,485 INFO exited: callback-receiver (exit status 1; not expected)
2021-05-06 07:03:35,485 INFO exited: callback-receiver (exit status 1; not expected)
2021-05-06 07:03:35,512 INFO spawned: 'callback-receiver' with pid 39
2021-05-06 07:03:35,512 INFO spawned: 'callback-receiver' with pid 39
2021-05-06 07:03:35,776 DEBUG    [-] awx.main.dispatch task ce3c5fef-3e5d-463b-ac5a-ae098a3270dc starting awx.main.tasks.apply_cluster_membership_policies(*[])
2021-05-06 07:03:35,820 DEBUG    [-] awx.main.tasks Waited 0.03499770164489746 seconds to obtain lock name: cluster_policy_lock
2021-05-06 07:03:35,849 DEBUG    [-] awx.main.tasks Total instances: 1, available for policy: 1
2021-05-06 07:03:35,850 DEBUG    [-] awx.main.tasks Policy percentage, adding Instances [33] to Group tower
2021-05-06 07:03:35,851 DEBUG    [-] awx.main.tasks Skipping containerized group tower for policy calculation
2021-05-06 07:03:35,852 DEBUG    [-] awx.main.tasks Cluster policy computation finished in 0.020956993103027344 seconds
2021-05-06 07:03:36,855 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:36,855 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-05-06 07:03:37,536 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:46
2021-05-06 07:03:37,536 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:46
2021-05-06 07:03:37,548 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:47
2021-05-06 07:03:37,548 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:47
2021-05-06 07:03:37,554 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:48
2021-05-06 07:03:37,554 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:48
2021-05-06 07:03:37,561 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:49
2021-05-06 07:03:37,561 WARNING  [-] awx.main.commands.run_callback_receiver scaling up worker pid:49
2021-05-06 07:03:37,564 DEBUG    [-] awx.main.commands.run_callback_receiver 39 is alive
2021-05-06 07:03:37,564 DEBUG    [-] awx.main.commands.run_callback_receiver 39 is alive
2021-05-06 07:03:55,174 DEBUG    [eb674eec60514f37b4c2f7184c28b7eb] awx.main.dispatch task 845643f2-0a3e-4b78-bb7a-057c0c018bd5 starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-05-06 07:03:55,180 DEBUG    [eb674eec60514f37b4c2f7184c28b7eb] awx.main.scheduler Running task manager.
2021-05-06 07:03:55,225 DEBUG    [eb674eec60514f37b4c2f7184c28b7eb] awx.main.scheduler Starting Scheduler
2021-05-06 07:03:55,220 DEBUG    [eb674eec60514f37b4c2f7184c28b7eb] awx.main.dispatch task 8029d664-c15a-4d5b-b5f8-1b1f6eff9dd6 starting awx.main.analytics.analytics_tasks.send_subsystem_metrics(*[])
2021-05-06 07:03:55,303 DEBUG    [eb674eec60514f37b4c2f7184c28b7eb] awx.main.scheduler Finishing Scheduler
```

![image](https://user-images.githubusercontent.com/59044937/117258554-624f2180-ae4d-11eb-9486-e37b596036bd.png)

**Comment by MrBones757** [comment]
I'm also seeing this issue, is there any known workaround for this?
I'm using a standard AWX operator based deployment using v0.9.0 with awx 19.1.0
Kubernetes v1.16.x

I have been able to register the ungrouped instance by creating an instance group and setting the policy to 100%, however capacity shows as "Unavailable" despite now having an assigned instance in this test group.

Also noted, in the task container there are logs like "Instance Group already registered tower" - seems something is creating the tower instance group as a cg but task is trying to create it as an ig

Before
![image](https://user-images.githubusercontent.com/22608473/119338764-fd0b8500-bcc2-11eb-8f43-dbb1e6d1543f.png)
Group:
![image](https://user-images.githubusercontent.com/22608473/119338802-08f74700-bcc3-11eb-8b9d-a988a0939d1e.png)
After:
![image](https://user-images.githubusercontent.com/22608473/119338830-11e81880-bcc3-11eb-9ef6-dca4dce3201c.png)
![image](https://user-images.githubusercontent.com/22608473/119338877-1d3b4400-bcc3-11eb-957b-7a024f133ccc.png)

Seems the default ee container is tryign to register as an old "instance" group rather than a "container" group?

**Comment by MrBones757** [comment]
Another interesting observation, it appears your can use the "run command" feature of an inventory and it successfully spins up a new container, however if you run a job with the same EE it fails. Not this occurs for the default EE 0.2.0 and a custom EE based off 0.2.0.

**Comment by MrBones757** [comment]
Update Again, A fresh install of AWX works, but for some reason our database migrated from 17.0.1 does not work
I have looked at tables (main_instance, main_instancegroup, main_executionenvironment, main_project, conf_setting, main_organization) and compared between a fresh instance and my instance using the same containers, ees, deployment etc (only difference being awx self managed db for the new instance and external db for our old one)

i cant see any major differences in these tables that could cause jobs to not start (ive defined default EEs in settings and the project but still no progress).

Just for laughs i created a new project based on the demo one, and this worked in our OLD migrated instance. strange.
Likewise createing a new job template that uses the hello-word play also works.

Currently - ad hoc commands work
                - project updates stay in running state with no output (same for any job) that existed prior to upgrade
                - new projects work when not using old credential
                - new job templates using new projects work
                - updating the old SCM credential private key and pass phrase make it work again for updates

**Comment by wenottingham** [comment]
Hi - we are resolving this in a combination of the awx operator and a new version of AWX (19.2.1 or later) that changes the default instance group used by the control plane. That should fix this.

**Comment by wenottingham** [comment]
Closing - please retry with 19.2.1, which should be released in the next day or so.
