### ISSUE TITLE
Can't access AWX Web UI after Minikube Deployment

### ISSUE THREAD

**Issue by cira-jonathan** [ansible/tower-operator#309]
I've deployed a new instance of awx using minikube and I can not access the web UI after following the deployment instructions. I've confirmed that all the containers have been deployed correctly (command output below):

minikube kubectl get pods

NAME                                                 READY  STATUS      RESTARTS   AGE
awx-5b58db49c-8d5n9                      4/4        Running    8                 3d14h
awx-operator-5595d6fc57-7fqxh       1/1        Running    3                 3d14h
awx-postgres-0                                  1/1        Running    3                 3d14h

However when I try and hit the service URL I am unable to get a landing page. I did however do some troubleshooting of the application pod and got the following output:

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "awx-postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 81, in _ctit_db_wrapper
    yield
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 411, in __getattr__
    value = self._get_local(name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 333, in _get_local
    self._preload_cache()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 296, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor = self.connection.cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "awx-postgres" to address: Name or service not known

WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0x12983d0 pid: 31 (default app)
2021-05-14 13:20:42,789 ERROR    [-] awx.conf.settings Database settings are not available, using defaults.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "awx-postgres" to address: Name or service not known
```

So it appears there's a potential issue with connecting to the postgres database pod. From reading the deployment documentation there doesn't seem to be any portion that refers to any sort of specific postgres configuration. This is the document I am following: https://github.com/ansible/awx/blob/devel/INSTALL.md

Any help in this matter would be greatly appreciated.

Here's some more information about my set up:
- Minikube version 1.18.1
- AWX Operator 0.9.0
- OS RHEL 7

**Comment by tchellomello** [comment]
@cira-jonathan it looks like the resolution of your cluster is not working. If you connect on your `awx` pod, are you able to resolve names? For instance: <podname>.<namespace>?  Do you have any particular `dnsPolicy` set on your cluster? 

Have you checked the `/etc/tower/conf.d/credentials.py` look as expected?

**Comment by cira-jonathan** [comment]
@tchellomello Here's a the output from `kubectl get pods`

```
NAME                            READY   STATUS    RESTARTS   AGE
awx-5b58db49c-8d5n9             4/4     Running   12         16d
awx-operator-5595d6fc57-7fqxh   1/1     Running   4          16d
awx-postgres-0                  1/1     Running   4          16d
```

I've connected to each of the pods and I'm unable to use any tools such as `ping` or `nslookup`. I just get a `command not found` error. I do not have any particular dnsPolicy set on my cluster. I'm just following the instructions found here: https://github.com/ansible/awx/blob/devel/INSTALL.md

Also, when I logged into each pod I checked the directory structure for the file you mentioned in your earlier message and I was unable to find that file.

**Comment by tchellomello** [comment]
Can you try something like this? 

**note**: for your end, user the pod name `awx-5b58db49c-8d5n9`. So replace `awx-sa-annotations` by `awx` on your end.
```yaml
$ kubectl get pods -l "app.kubernetes.io/managed-by=awx-operator"     15:59:44
NAME                                 READY   STATUS    RESTARTS   AGE
awx-sa-annotations-8c78d944f-5zpr2   4/4     Running   0          24h
awx-sa-annotations-postgres-0        1/1     Running   0          2d3h

$ kubectl exec --stdin --tty awx-sa-annotations-8c78d944f-5zpr2 -c awx-sa-annotations-task -- /bin/bash
bash-4.4$ cat /etc/tower/conf.d/credentials.py 
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx",
        'USER': "awx",
        'PASSWORD': "hoWSRm1bY9T1eY1xLAmS0rd3TiKpCeIY",
        'HOST': 'awx-sa-annotations-postgres',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "ylhxKlUytxA1LY3AkZ95NJjHnfZWmMg0"


bash-4.4$ ping awx-sa-annotations-postgres -c 1
PING awx-sa-annotations-postgres.default.svc.cluster.local (10.233.65.76) 56(84) bytes of data.
64 bytes from 10-233-65-76.awx-sa-annotations-postgres.default.svc.cluster.local (10.233.65.76): icmp_seq=1 ttl=64 time=0.041 ms

--- awx-sa-annotations-postgres.default.svc.cluster.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.041/0.041/0.041/0.000 ms
```
Another thing you can do is start a new pod using the dnstools on the same namespace and you can troubleshoot it.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dnstools
  labels:
    app: dnstools
spec:
  containers:
    - name: dnstools 
      image: infoblox/dnstools:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
```

Then on this pod, you should be able to run command commands and test the DNS resolution

```yaml
kubectl get pods -l app=dnstools    16:07:18
NAME       READY   STATUS    RESTARTS   AGE
dnstools   1/1     Running   0          18s

$ kubectl exec --stdin --tty dnstools -- /bin/sh
$ dnstools# nslookup  awx-sa-annotations-postgres.default.svc
Server:		169.254.25.10
Address:	169.254.25.10#53

Name:	awx-sa-annotations-postgres.default.svc.cluster.local
Address: 10.233.65.76

dnstools# nc -vv awx-sa-annotations-postgres.default.svc.cluster.local 5432
awx-sa-annotations-postgres.default.svc.cluster.local (10.233.65.76:5432) open
^Csent 0, rcvd 0
punt!

```

**Comment by cira-jonathan** [comment]
@tchellomello Ran those commands you suggested and got the following output...

```
[awx@crp-awx-01 ~]$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
awx-5b58db49c-8d5n9             4/4     Running   24         17d
awx-operator-5595d6fc57-7fqxh   1/1     Running   8          17d
awx-postgres-0                  1/1     Running   7          17d
dnstools                        1/1     Running   2          104m
[awx@crp-awx-01 ~]$ kubectl get pods -l "app.kubernetes.io/managed-by=awx-operator"
NAME                  READY   STATUS    RESTARTS   AGE
awx-5b58db49c-8d5n9   4/4     Running   24         17d
awx-postgres-0        1/1     Running   7          17d
[awx@crp-awx-01 ~]$ kubectl exec --stdin --tty awx-5b58db49c-8d5n9 -c awx-task -- /bin/bash
bash-4.4$ cat /etc/tower/conf.d/credentials.py
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx",
        'USER': "awx",
        'PASSWORD': "kcXyZpyjBlJFuic78JvxNcNZPzRrGO3U",
        'HOST': 'awx-postgres',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "AEhV4bkNVIuBOAPRKaqlXY2Ce05hYZwF"
bash-4.4$ ping awx-postgres -c 1
PING awx-postgres.default.svc.cluster.local (172.17.0.8) 56(84) bytes of data.
64 bytes from 172-17-0-8.awx-postgres.default.svc.cluster.local (172.17.0.8): icmp_seq=1 ttl=64 time=0.049 ms

--- awx-postgres.default.svc.cluster.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.049/0.049/0.049/0.000 ms
bash-4.4$ exit
exit
[awx@crp-awx-01 ~]$ kubectl exec --stdin --tty dnstools -- /bin/sh
dnstools# nslookup  awx-postgres.default.svc
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   awx-postgres.default.svc.cluster.local
Address: 172.17.0.8

dnstools# nc -vv awx-postgres.default.svc.cluster.local
nc: bad address 'awx-postgres.default.svc.cluster.local'
dnstools# nc -vv awx-postgres.default.svc.cluster.local 5432
nc: bad address 'awx-postgres.default.svc.cluster.local'
dnstools#
```

**Comment by tchellomello** [comment]
@cira-jonathan dns seems to be fine. Let's check your `pgsql` pod.  I noticed that your pod has 7 restarts. 

```
awx-postgres-0                  1/1     Running   7          17d
```
What is the output for the commands below:

```bash
kubectl describe pod awx-postgres-0
```

Then if you connect to the `awx-postgres-0` are you able to connect to the database locally?

```yaml
$ kubectl iexec awx-sa- /bin/bash                                                                                                                                                     10:45:51
Namespace: default | Pod: ✔ awx-sa-annotations-postgres-0
root@awx-sa-annotations-postgres-0:/# psql  -h localhost -U awx awx 
Password for user awx: 
psql (12.7 (Debian 12.7-1.pgdg100+1))
Type "help" for help.
```

**Comment by ctournoux-maincare** [comment]
Hello,

I have the same problem but I think I have a dns problem :

```
[awx@ansiawx ~]$ minikube  kubectl -- get svc
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
awx-nginx-postgres     ClusterIP   None            <none>        5432/TCP            63m
awx-nginx-service      ClusterIP   10.106.51.229   <none>        80/TCP              62m
awx-operator-metrics   ClusterIP   10.101.128.97   <none>        8383/TCP,8686/TCP   64m
kubernetes             ClusterIP   10.96.0.1       <none>        443/TCP             67m
```
```
bash-4.4$ cat /etc/tower/conf.d/credentials.py
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx",
        'USER': "awx",
        'PASSWORD': "yPs6kBex8bbd2adCfqOVlNLtkZypqxVo",
        'HOST': 'awx-nginx-postgres',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "QGHEXsCY5JEjpRCTlvOttocnRKmPZmIn"
bash-4.4$ ping awx-nginx-postgres -c 1
ping: awx-nginx-postgres: Name or service not known
```

```
[awx@ansiawx ~]$ minikube  kubectl -- exec --stdin --tty dnstools -- /bin/sh
dnstools# nslookup  awx-nginx-postgres.default.svc
;; reply from unexpected source: 10.244.0.3#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.3#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.3#53, expected 10.96.0.10#53
;; connection timed out; no servers could be reached
```

How I can resolv that ?

**Comment by DieWeb21** [comment]
Hello,

I have exactly the same problem as @ctournoux-maincare 

`
Traceback (most recent call last):
File "/usr/bin/awx-manage", line 8, in <module>
sys.exit(manage())
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 155, in manage
if (connection.pg_version // 10000) < 12:
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
return getattr(connections[DEFAULT_DB_ALIAS], item)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
res = instance.__dict__[self.name] = self.func(instance)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 282, in pg_version
with self.temporary_connection():
File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
return next(self.gen)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 593, in temporary_connection
with self.cursor() as cursor:
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
return self._cursor()
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
self.ensure_connection()
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
self.connect()
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
self.connect()
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
self.connection = self.get_new_connection(conn_params)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
connection = Database.connect(**conn_params)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "awx-postgres" to address: Name or service not known
`

Is there any fix to this problem ?

**Comment by ctournoux-maincare** [comment]
I still have the problem in the latest versions of the operator

Any solution to solve postgres name resolution problem ?

**Comment by cira-jonathan** [comment]
The cause of my issue was my networking set up on my end. Based on how our network/security was set up, I needed port forwarding enabled in order to forward the port to the pod.

**Comment by tchellomello** [comment]
@cira-jonathan Thanks for the feedback and since it has been fixed on your end, I'm closing this issue. Thanks!
