### ISSUE TITLE
RuntimeError: Error creating pod: container failed with exit code 1: 

### ISSUE THREAD

**Issue by golgotow** [ansible/tower-operator#391]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
every job ends in similar error 

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1384, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2900, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2963, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: container failed with exit code 1: 

##### ENVIRONMENT
* AWX version: 19.2.0
* Operator version: quay.io/ansible/awx-operator:0.10.0
* Kubernetes version:  v1.20.7+k3s1
* AWX install method: via operator
* 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-extra-config
  namespace: awx
data:
  ansible.cfg: |
     [defaults]
     remote_tmp = /tmp
     [ssh_connection]
     ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: LoadBalancer
  hostname: awx.domain.local
  task_privileged: true
  node_selector: |
    kubernetes.io/arch: amd64
  projects_persistence: true
  projects_storage_size: 20Gi
  projects_storage_class: rook-cephfs

##### STEPS TO REPRODUCE

new install on k3s cluster, tried 3x with same issue during run of job.
Same cluster is installed and from web gui all looks ok, expect for template run

##### EXPECTED RESULTS

no error during job.
Way to look for issue

##### ADDITIONAL INFORMATION

during job playbook end like 

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1384, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2900, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2963, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Stream error running pod: unable to upgrade connection: container worker not found in pod automation-job-3-kbg28_awx

or 

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1384, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2900, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2963, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Error creating pod: container failed with exit code 1: 

##### AWX-OPERATOR LOGS
[container.log](https://github.com/ansible/awx-operator/files/6645813/container.log)

**Comment by tchellomello** [comment]
@golgotow we are not seeing any issues on the operator level itself. 
```yaml
--------------------------- Ansible Task Status Event StdOut  ----------------- 
 
PLAY RECAP ********************************************************************* 
localhost                  : ok=49   changed=2    unreachable=0    failed=0    skipped=34   rescued=0    ignored=0 
 ```

Having said this, do you see this only when running jobs, right? Can you send us your POD spec?

**Comment by golgotow** [comment]
@tchellomello can you let me know what exactly you need to investigate ?
[spec.txt](https://github.com/ansible/awx-operator/files/6650113/spec.txt)

**Comment by RogerSik** [comment]
We had the same issue. In our case the problem was 
```  
node_selector: |
    environment: awx
    kubernetes.io/arch: amd64
```

the operator is ignoring node_selector (is verifiable with 'k describe pod operator') and gets randoming scheduled to a node. In our case the operator get scheduled on an ARM Node and always exited with the 
```
RuntimeError: Error creating pod: container failed with exit code 1:
```

**Comment by astehlik** [comment]
I think there are two different issues:

1. The operator-controller-manager does not get the nodeSelector config. This is described in #1237 and there is a workaround documented.
2. The pod that is started to execute the job (`awx-ee`) also has no nodeSelector config. I did not find a workaround for this yet :(

This is an excerpt of the `kubectl describe` command of the `automation-job` Pod:

```yaml
Name:         automation-job-70710-79fdh
Namespace:    awx
Status:       Running
Containers:
  worker:
    Image:        quay.io/ansible/awx-ee:latest
    Requests:
      cpu:        250m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
Node-Selectors:     <none>
```
