### ISSUE TITLE
AWX-Demo 504 Gateway Timeout

### ISSUE THREAD

**Issue by jacksondaw** [ansible/tower-operator#467]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Ran through the basic installation on AKS. After applying the awx.yaml below, webpage returns 504 Gateway Timeout.

awx.yaml 
```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: demo
spec:
  service_type: ClusterIP
  service_labels: |
    environment: nonprod
  ingress_type: ingress
  ingress_annotations: "kubernetes.io/ingress.class: nginx-internal"
  
  ingress_tls_secret: demo-tls
  hostname: awx.local
  web_resource_requirements:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 250m
      memory: 256Mi
  task_resource_requirements:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 250m
      memory: 256Mi
  ee_resource_requirements:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 250m
      memory: 256Mi
```

##### ENVIRONMENT
* Operator version: 0.11.0/0.12.0
* Kubernetes version: 1.19
* AWX install method: Followed installation instructions in read me

##### STEPS TO REPRODUCE

Deploy to cluster using default configuration. Apply awx.yaml provided

##### EXPECTED RESULTS

Login page displayed.

##### ACTUAL RESULTS

Nginx 504 Timeout error. 

##### ADDITIONAL INFORMATION

Redis and ee pods have no errors in logs

Log from awx-demo-web pod
```
2021-07-13 23:47:15,470 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:47:15,470 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:47:15,477 INFO exited: awx-rsyslogd (exit status 1; not expected)
2021-07-13 23:47:15,477 INFO exited: awx-rsyslogd (exit status 1; not expected)
2021-07-13 23:47:16,544 INFO spawned: 'awx-rsyslogd' with pid 177
2021-07-13 23:47:16,544 INFO spawned: 'awx-rsyslogd' with pid 177
rsyslogd: could not open config file '/var/lib/awx/rsyslog/rsyslog.conf': No such file or directory [v8.1911.0-7.el8_4.2 try https://www.rsyslog.com/e/2104 ]
rsyslogd: run failed with error -2104 (see rsyslog.h or try https://www.rsyslog.com/e/2104 to learn what that number means)
2021-07-13 23:47:17,753 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:47:17,753 INFO success: awx-rsyslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:47:17,755 INFO exited: awx-rsyslogd (exit status 1; not expected)
2021-07-13 23:47:17,755 INFO exited: awx-rsyslogd (exit status 1; not expected)
2021-07-13 23:47:18,839 INFO spawned: 'awx-rsyslogd' with pid 178
2021-07-13 23:47:18,839 INFO spawned: 'awx-rsyslogd' with pid 178
2021-07-13 23:47:19,438 INFO exited: daphne (terminated by SIGKILL; not expected)
2021-07-13 23:47:19,438 INFO exited: daphne (terminated by SIGKILL; not expected)
rsyslogd: could not open config file '/var/lib/awx/rsyslog/rsyslog.conf': No such file or directory [v8.1911.0-7.el8_4.2 try https://www.rsyslog.com/e/2104 ]
2021-07-13 23:47:19,543 INFO spawned: 'daphne' with pid 179
2021-07-13 23:47:19,543 INFO spawned: 'daphne' with pid 179
rsyslogd: run failed with error -2104 (see rsyslog.h or try https://www.rsyslog.com/e/2104 to learn what that number means)
2021-07-13 23:47:19,545 INFO exited: awx-rsyslogd (exit status 1; not expected)
2021-07-13 23:47:19,545 INFO exited: awx-rsyslogd (exit status 1; not expected)
DAMN ! worker 2 (pid: 151) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 2 (new pid: 180)
```

awx-demo-task log
```
eturn self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column main_instance.ip_address does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance...
^
2021-07-13 23:52:47,167 INFO exited: callback-receiver (terminated by SIGKILL; not expected)
2021-07-13 23:52:47,167 INFO exited: callback-receiver (terminated by SIGKILL; not expected)
2021-07-13 23:52:48,176 INFO spawned: 'callback-receiver' with pid 270
2021-07-13 23:52:48,176 INFO spawned: 'callback-receiver' with pid 270
2021-07-13 23:52:49,239 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:52:49,239 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:52:50,657 INFO exited: dispatcher (exit status 1; not expected)
2021-07-13 23:52:50,657 INFO exited: dispatcher (exit status 1; not expected)
2021-07-13 23:52:51,663 INFO spawned: 'dispatcher' with pid 272
2021-07-13 23:52:51,663 INFO spawned: 'dispatcher' with pid 272
2021-07-13 23:52:52,665 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:52:52,665 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
RESULT 2
OKREADY
Traceback (most recent call last):
File "/usr/bin/awx-manage", line 8, in <module>
sys.exit(manage())
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 171, in manage
execute_from_command_line(sys.argv)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
self.execute(*args, **cmd_options)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
output = self.handle(*args, **options)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/run_callback_receiver.py", line 31, in handle
CallbackBrokerWorker(),
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/worker/callback.py", line 49, in __init__
self.subsystem_metrics = s_metrics.Metrics(auto_pipe_execute=False)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/analytics/subsystem_metrics.py", line 153, in __init__
self.instance_name = Instance.objects.me().hostname
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/managers.py", line 112, in me
raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
2021-07-13 23:53:09,844 WARNING [-] awx.main.dispatch.periodic periodic beat started
2021-07-13 23:53:10,654 INFO exited: dispatcher (terminated by SIGKILL; not expected)
2021-07-13 23:53:10,654 INFO exited: dispatcher (terminated by SIGKILL; not expected)
2021-07-13 23:53:10,656 INFO spawned: 'dispatcher' with pid 279
2021-07-13 23:53:10,656 INFO spawned: 'dispatcher' with pid 279
2021-07-13 23:53:10,663 INFO exited: callback-receiver (exit status 1; not expected)
2021-07-13 23:53:10,663 INFO exited: callback-receiver (exit status 1; not expected)
2021-07-13 23:53:11,666 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:53:11,666 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:53:11,668 INFO spawned: 'callback-receiver' with pid 281
2021-07-13 23:53:11,668 INFO spawned: 'callback-receiver' with pid 281
2021-07-13 23:53:12,738 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:53:12,738 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
File "/usr/bin/awx-manage", line 8, in <module>
sys.exit(manage())
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 171, in manage
execute_from_command_line(sys.argv)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
self.execute(*args, **cmd_options)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
output = self.handle(*args, **options)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/management/commands/run_callback_receiver.py", line 31, in handle
CallbackBrokerWorker(),
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/worker/callback.py", line 49, in __init__
self.subsystem_metrics = s_metrics.Metrics(auto_pipe_execute=False)
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/analytics/subsystem_metrics.py", line 153, in __init__
self.instance_name = Instance.objects.me().hostname
File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/managers.py", line 112, in me
raise RuntimeError("No instance found with the current cluster host id")
RuntimeError: No instance found with the current cluster host id
2021-07-13 23:53:31,258 INFO exited: dispatcher (terminated by SIGKILL; not expected)
2021-07-13 23:53:31,258 INFO exited: dispatcher (terminated by SIGKILL; not expected)
2021-07-13 23:53:31,260 INFO spawned: 'dispatcher' with pid 288
2021-07-13 23:53:31,260 INFO spawned: 'dispatcher' with pid 288
2021-07-13 23:53:32,262 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:53:32,262 INFO success: dispatcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:53:34,962 INFO exited: callback-receiver (exit status 1; not expected)
2021-07-13 23:53:34,962 INFO exited: callback-receiver (exit status 1; not expected)
2021-07-13 23:53:35,968 INFO spawned: 'callback-receiver' with pid 290
2021-07-13 23:53:35,968 INFO spawned: 'callback-receiver' with pid 290
2021-07-13 23:53:37,039 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:53:37,039 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-13 23:53:52,150 INFO exited: dispatcher (terminated by SIGKILL; not expected)
2021-07-13 23:53:52,150 INFO exited: dispatcher (terminated by SIGKILL; not expected)
2021-07-13 23:53:52,152 INFO spawned: 'dispatcher' with pid 297
2021-07-13 23:53:52,152 INFO spawned: 'dispatcher' with pid 297
```

**Comment by JonathanG3** [comment]
Hey, I also had this issue, I've gone from 0.13.0 to 0.12.0 because I understood that there is an issue with the External DB configuration in 0.13.0 which is something I plan on doing on the future.

After downgrading to 0.12.0, I added ingress configuration using NGINX and it seems like that since then my jobs couldn't run anymore.

Returning to 0.13.0 fixed the issue for me.
