### ISSUE TITLE
Decryption fails when migrating from old Instance

### ISSUE THREAD

**Issue by techBeck03** [ansible/tower-operator#595]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After deploying a new AWX instance (`19.4.0`) from an older one (`19.0.0`) by following the migration [guide](https://github.com/ansible/awx-operator/blob/0.14.0/docs/migration.md), it seems the `secret_key` is not correctly being used to decrypt files.  I can login to the UI, see all of my configuration from the old instance is there, but when I try to run a job it immediately fails.

##### ENVIRONMENT
* AWX version: `19.4.0`
* Operator version: `0.14.0`
* Kubernetes version: `1.21.4`
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

I followed the migration guide and created a secret for both my old Postgres instance and the `secret_key`.  The data is successfully migrated so I know the database secret worked correctly.  Below is the format I used for the secret_key:

```yaml
---
apiVersion: v1
data:
  secret_key: dGhpc0lzTm90TXlSZWFsU2VjcmV0Cg== # redacted but wanted to show I know it's base64 encoded
kind: Secret
metadata:
  name: awx-wwdc-secret-key # my resource name is 'awx-wwdc'
  namespace: awx-blue
type: Opaque
```

##### EXPECTED RESULTS

Data is migrated and job runs work as expected

##### ACTUAL RESULTS

Data is migrated, everything shows up in the UI, I can login correctly, I can view credentials/inventories/templates/settings/etc., but when I got to launch a job it immediately fails with the following error:

```python
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/encryption.py", line 145, in decrypt_field
    value = instance.inputs[field_name]
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 278, in get_input
    return decrypt_field(self, field_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/encryption.py", line 149, in decrypt_field
    raise AttributeError(field_name)
AttributeError: password

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1499, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3029, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3056, in _run_internal
    result = receptor_ctl.submit_work(worktype=self.work_type, payload=sockout.makefile('rb'), params=self.receptor_params, **_kw)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3141, in receptor_params
    spec_yaml = yaml.dump(self.pod_definition, explicit_start=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3212, in pod_definition
    secret_name = pm.create_secret(job=self.task.instance)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 70, in create_secret
    password = registry_cred.get_input("password")
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 285, in get_input
    raise AttributeError
AttributeError
```

##### AWX-OPERATOR LOGS
```python
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/encryption.py", line 145, in decrypt_field
    value = instance.inputs[field_name]
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 278, in get_input
    return decrypt_field(self, field_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/utils/encryption.py", line 149, in decrypt_field
    raise AttributeError(field_name)
AttributeError: password

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1499, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3029, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3056, in _run_internal
    result = receptor_ctl.submit_work(worktype=self.work_type, payload=sockout.makefile('rb'), params=self.receptor_params, **_kw)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3141, in receptor_params
    spec_yaml = yaml.dump(self.pod_definition, explicit_start=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3212, in pod_definition
    secret_name = pm.create_secret(job=self.task.instance)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 70, in create_secret
    password = registry_cred.get_input("password")
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/models/credential/__init__.py", line 285, in get_input
    raise AttributeError
AttributeError
```

**Comment by techBeck03** [comment]
As an update I've verified the secret key is correct on **task** using:

```bash
❯ k exec -i -t wwdc-558cf4b67c-fgj4h -c wwdc-task -- bash
bash-4.4$ awx-manage shell_plus --quiet
Python 3.8.6 (default, Jan 29 2021, 17:38:16) 
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> settings.SECRET_KEY
```

and **web** using:

```bash
❯ k exec -i -t wwdc-558cf4b67c-fgj4h -c wwdc-web -- bash
bash-4.4$ cat /etc/tower/SECRET_KEY 
```

Both show the correct value yet I'm still having this error.  Thanks!

**Comment by techBeck03** [comment]
Well this issue was actually tied to my docker registry credential. Apparently in the older version there were two separate fields for password and token but in the new release this is all one field.  That was the underlying issue.

Thanks!
