### ISSUE TITLE
Jobs are randomly marked as failed

### ISSUE THREAD

**Issue by backaf** [ansible/tower-operator#650]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Jobs are randomly marked as failed, before they are even started. There are no errors in the job output. On the Kubernetes side, I can see the following:

```
DEBUG 2021/11/12 10:44:18 Sending service advertisement: &{awx-67868d4bd4-rbjmv control 2021-11-12 10:44:18.9370594 +0000 UTC m=+125.536662987 1 map[type:Control Service] [{local false} {kubernetes-runtime-auth false} {kubernetes-incluster-auth false}]}
INFO 2021/11/12 10:44:21 Stdout complete - closing channel for: wD574Yl0
ERROR 2021/11/12 10:44:21 Read error in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
INFO 2021/11/12 10:44:21 Client disconnected from control service
ERROR 2021/11/12 10:44:21 Error closing connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection
INFO 2021/11/12 10:44:21 Client connected to control service
INFO 2021/11/12 10:44:21 Control service closed
INFO 2021/11/12 10:44:21 Client disconnected from control service
INFO 2021/11/12 10:44:22 Client connected to control service
INFO 2021/11/12 10:44:22 Control service closed
INFO 2021/11/12 10:44:22 Client disconnected from control service
INFO 2021/11/12 10:44:22 Client connected to control service
INFO 2021/11/12 10:44:22 Control service closed
INFO 2021/11/12 10:44:22 Client disconnected from control service
INFO 2021/11/12 10:44:22 Client connected to control service
INFO 2021/11/12 10:44:22 Control service closed
INFO 2021/11/12 10:44:22 Client disconnected from control service
INFO 2021/11/12 10:44:22 Client connected to control service
INFO 2021/11/12 10:44:28 Client connected to control service
INFO 2021/11/12 10:44:35 Control service closed
INFO 2021/11/12 10:44:35 Client disconnected from control service
ERROR 2021/11/12 10:44:35 Error creating pod: Unauthorized
INFO 2021/11/12 10:44:35 Client connected to control service
WARNING 2021/11/12 10:44:35 Unit completed without producing any stdout
```

![Screen Shot 2021-11-12 at 12 03 03](https://user-images.githubusercontent.com/22817887/141458133-50506ae9-79bf-45e0-9e49-210307f582f8.png)
![Screen Shot 2021-11-12 at 12 03 47](https://user-images.githubusercontent.com/22817887/141458140-0239f900-19f7-47e2-b2f3-8a2edf80c3ea.png)

This happens independent on the template or execution environment. In all situations, restarting the job will fix the issue. 

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: v1.22.2
* AWX install method: 

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: ClusterIP
  ingress_type: ingress
  hostname: "awx-beta.company.com"
  ingress_tls_secret: "company-com-ssl"
  ingress_annotations: |
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
```

##### STEPS TO REPRODUCE

There are no clear reproduction steps, it fails randomly. 

##### EXPECTED RESULTS

Job should succeed.

##### ACTUAL RESULTS

Job failed.

##### AWX-OPERATOR LOG
[controller.txt](https://github.com/ansible/awx-operator/files/7527119/controller.txt)

**Comment by chrismeyersfsu** [comment]
@backaf Can you give us the API endpoint of the failed job here? Also, the task container log roughly around the time a failure happens. Please correlate the timestamps of the job runtime and the logs to help us.

**Comment by backaf** [comment]
@chrismeyersfsu - here's another similar failed job (id 163):

**awx-task:**

```
2021-11-16 00:01:04,307 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.tasks project_update 164 (running) wrote to cache at /var/lib/awx/projects/.__awx_cache/_10__onboarding/164
2021-11-16 00:01:04,580 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.analytics.job_lifecycle projectupdate-164 finalize run
2021-11-16 00:01:04,586 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.dispatch task bde9cc7b-2123-4b98-9461-35f794fa2727 starting awx.main.tasks.handle_work_success(*[])
2021-11-16 00:01:04,626 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.dispatch task 365cbcbe-4a5e-4326-9307-0916909baa3d starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-11-16 00:01:04,627 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.scheduler Running task manager.
2021-11-16 00:01:04,666 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.scheduler Starting Scheduler
2021-11-16 00:01:05,025 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.analytics.job_lifecycle job-163 waiting
2021-11-16 00:01:05,026 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.scheduler job 163 (waiting) consumed 6 capacity units from default with prior total of 0
2021-11-16 00:01:05,027 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.scheduler Finishing Scheduler
2021-11-16 00:01:05,202 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.dispatch task 2b18b7b6-237c-4cc2-87db-5129ac6da2f7 starting awx.main.tasks.RunJob(*[163])
2021-11-16 00:01:05,591 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.analytics.job_lifecycle job-163 pre run
2021-11-16 00:01:05,605 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.tasks Skipping project sync for job 163 (running) because commit is locally available
2021-11-16 00:01:06,663 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.tasks Project 10 prepared /tmp/awx_163_txngleu3/requirements_collections from cache
2021-11-16 00:01:06,666 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.analytics.job_lifecycle job-163 preparing playbook
2021-11-16 00:01:06,821 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.analytics.job_lifecycle job-163 running playbook
2021-11-16 00:01:08,708 INFO     [9524538bf75a42379361076a9f47ac5f] awx.main.commands.run_callback_receiver Event processing is finished for Job 163, sending notifications
2021-11-16 00:01:08,708 INFO     [9524538bf75a42379361076a9f47ac5f] awx.main.commands.run_callback_receiver Event processing is finished for Job 163, sending notifications
2021-11-16 00:01:09,761 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.tasks job 163 (running) finished running, producing 0 events.
2021-11-16 00:01:09,773 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.analytics.job_lifecycle job-163 post run
2021-11-16 00:01:09,891 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.analytics.job_lifecycle job-163 finalize run
2021-11-16 00:01:09,920 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.dispatch task aea6f8b8-2845-47a1-aeb8-33564220b77b starting awx.main.tasks.update_inventory_computed_fields(*[2])
2021-11-16 00:01:09,960 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.models.inventory Going to update inventory computed fields, pk=2
2021-11-16 00:01:09,985 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.models.inventory Finished updating inventory computed fields, pk=2, in 0.024 seconds
2021-11-16 00:01:10,142 WARNING  [9524538bf75a42379361076a9f47ac5f] awx.main.dispatch job 163 (error) encountered an error (rc=None), please see task stdout for details.
2021-11-16 00:01:10,143 DEBUG    [9524538bf75a42379361076a9f47ac5f] awx.main.dispatch task 2b18b7b6-237c-4cc2-87db-5129ac6da2f7 starting awx.main.tasks.handle_work_error(*['2b18b7b6-237c-4cc2-87db-5129ac6da2f7'])
```

**awx-ee:**
```
INFO 2021/11/16 00:01:03 Client connected to control service
INFO 2021/11/16 00:01:03 Control service closed
INFO 2021/11/16 00:01:03 Client disconnected from control service
INFO 2021/11/16 00:01:06 Client connected to control service
INFO 2021/11/16 00:01:08 Control service closed
INFO 2021/11/16 00:01:08 Client disconnected from control service
ERROR 2021/11/16 00:01:08 Error creating pod: Unauthorized
INFO 2021/11/16 00:01:08 Client connected to control service
WARNING 2021/11/16 00:01:08 Unit completed without producing any stdout
ERROR 2021/11/16 00:01:08 Read error in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
INFO 2021/11/16 00:01:08 Client disconnected from control service
ERROR 2021/11/16 00:01:08 Error closing connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection
INFO 2021/11/16 00:01:08 Client connected to control service
WARNING 2021/11/16 00:01:08 Unit completed without producing any stdout
ERROR 2021/11/16 00:01:08 Read error in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
INFO 2021/11/16 00:01:08 Client disconnected from control service
ERROR 2021/11/16 00:01:08 Error closing connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection
INFO 2021/11/16 00:01:09 Client connected to control service
ERROR 2021/11/16 00:01:09 Error deleting pod : resource name may not be empty
INFO 2021/11/16 00:01:09 Control service closed
```
[job-163-stdout.txt](https://github.com/ansible/awx-operator/files/7544293/job-163-stdout.txt)
[job-163.txt](https://github.com/ansible/awx-operator/files/7544294/job-163.txt)


Let me know if there's anything else I can provide.

**Comment by backaf** [comment]
Sometimes, I can see the following errors in logs when a job is marked with error:

```
2021-11-16 14:36:31,429 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.tasks Project 26 prepared /tmp/awx_186_ybwt8s8k/requirements_collections from cache
2021-11-16 14:36:31,433 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.analytics.job_lifecycle job-186 preparing playbook
2021-11-16 14:36:31,622 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.analytics.job_lifecycle job-186 running playbook
2021-11-16 14:36:31,693 ERROR    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.scheduler Invalid openshift or k8s cluster credential: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '19e03a61-4a7c-4077-9815-7764305273b5', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 16 Nov 2021 14:17:09 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 88, in create_secret
    existing_secret = self.kube_api.read_namespaced_secret(namespace=self.namespace, name=secret_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20110, in read_namespaced_secret
    (data) = self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20187, in read_namespaced_secret_with_http_info
    return self.api_client.call_api(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 362, in request
    return self.rest_client.GET(url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 237, in GET
    return self.request("GET", url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '19e03a61-4a7c-4077-9815-7764305273b5', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 16 Nov 2021 14:17:09 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}


2021-11-16 14:36:33,352 ERROR    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.tasks job 186 (running) Exception occurred while running task
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 88, in create_secret
    existing_secret = self.kube_api.read_namespaced_secret(namespace=self.namespace, name=secret_name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20110, in read_namespaced_secret
    (data) = self.read_namespaced_secret_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 20187, in read_namespaced_secret_with_http_info
    return self.api_client.call_api(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/api_client.py", line 362, in request
    return self.rest_client.GET(url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 237, in GET
    return self.request("GET", url,
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '19e03a61-4a7c-4077-9815-7764305273b5', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 16 Nov 2021 14:17:09 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1499, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3029, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3056, in _run_internal
    result = receptor_ctl.submit_work(worktype=self.work_type, payload=sockout.makefile('rb'), params=self.receptor_params, **_kw)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3141, in receptor_params
    spec_yaml = yaml.dump(self.pod_definition, explicit_start=True)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3212, in pod_definition
    secret_name = pm.create_secret(job=self.task.instance)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/scheduler/kubernetes.py", line 105, in create_secret
    raise PermissionError(full_error_msg)
PermissionError: Invalid openshift or k8s cluster credential: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '19e03a61-4a7c-4077-9815-7764305273b5', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 16 Nov 2021 14:17:09 GMT', 'Content-Length': '129'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}


2021-11-16 14:36:33,356 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.tasks job 186 (running) finished running, producing 0 events.
2021-11-16 14:36:33,357 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.analytics.job_lifecycle job-186 post run
2021-11-16 14:36:33,672 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.analytics.job_lifecycle job-186 finalize run
2021-11-16 14:36:33,760 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.dispatch task 03d57254-b4e5-481a-a9d6-3b62fa2a4c8a starting awx.main.tasks.update_inventory_computed_fields(*[3])
2021-11-16 14:36:33,851 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.models.inventory Going to update inventory computed fields, pk=3
2021-11-16 14:36:33,891 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.models.inventory Finished updating inventory computed fields, pk=3, in 0.039 seconds
2021-11-16 14:36:34,192 DEBUG    [0292e1e89c5444c5a7fb741947ecc12a] awx.analytics.job_lifecycle job-186 event processing finished
2021-11-16 14:36:34,146 WARNING  [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.dispatch job 186 (error) encountered an error (rc=None), please see task stdout for details.
2021-11-16 14:36:34,149 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.dispatch task 01fbceae-b68c-408d-a40e-d926c77e1c52 starting awx.main.tasks.handle_work_error(*['01fbceae-b68c-408d-a40e-d926c77e1c52'])
2021-11-16 14:36:34,151 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.tasks Executing error task id 01fbceae-b68c-408d-a40e-d926c77e1c52, subtasks: [{'type': 'job', 'id': 186}]
2021-11-16 14:36:34,224 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.dispatch task 4dbf7057-f67b-4346-8377-34b898fbc411 starting awx.main.scheduler.tasks.run_task_manager(*[])
2021-11-16 14:36:34,226 DEBUG    [96349d3c6c984d2c850e6e1b8ddb667f] awx.main.scheduler Running task manager.
```

**Comment by chrismeyersfsu** [comment]
We think we are seeing this sometimes too but can't pin it down. Maybe there are some kind of rate limits? Do you have any thoughts on it might be?

Maybe it has to do with your role bindings. Could you post those?

**Comment by backaf** [comment]
I haven't really modified anything when I deployed the operator. The actual AWX deployment is light, I only configured the ingress. 

Info on roles:

```
$ kubectl get rolebindings.rbac.authorization.k8s.io -n awx
NAME                                       ROLE                                     AGE
awx                                        Role/awx                                 17d
awx-operator-leader-election-rolebinding   Role/awx-operator-leader-election-role   17d
awx-operator-manager-rolebinding           Role/awx-operator-manager-role           17d

$ kubectl get roles.rbac.authorization.k8s.io -n awx
NAME                                CREATED AT
awx                                 2021-11-03T09:14:46Z
awx-operator-leader-election-role   2021-11-02T10:49:31Z
awx-operator-manager-role           2021-11-02T10:49:32Z

kubectl describe roles.rbac.authorization.k8s.io -n awx awx-operator-leader-election-role
Name:         awx-operator-leader-election-role
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources                   Non-Resource URLs  Resource Names  Verbs
  ---------                   -----------------  --------------  -----
  events                      []                 []              [create patch]
  configmaps                  []                 []              [get list watch create update patch delete]
  leases.coordination.k8s.io  []                 []              [get list watch create update patch delete]


$ kubectl describe roles.rbac.authorization.k8s.io -n awx awx-operator-manager-role
  Name:         awx-operator-manager-role
  Labels:       <none>
  Annotations:  <none>
  PolicyRule:
    Resources                                         Non-Resource URLs  Resource Names  Verbs
    ---------                                         -----------------  --------------  -----
    *.awx.ansible.com                                 []                 []              [*]
    awxbackups.awx.ansible.com                        []                 []              [*]
    awxrestores.awx.ansible.com                       []                 []              [*]
    pods/attach                                       []                 []              [create get]
    pods/exec                                         []                 []              [create get]
    pods/log                                          []                 []              [create get]
    servicemonitors.monitoring.coreos.com             []                 []              [get create]
    configmaps                                        []                 []              [get list create delete patch update watch]
    endpoints                                         []                 []              [get list create delete patch update watch]
    events                                            []                 []              [get list create delete patch update watch]
    persistentvolumeclaims                            []                 []              [get list create delete patch update watch]
    pods                                              []                 []              [get list create delete patch update watch]
    rolebindings                                      []                 []              [get list create delete patch update watch]
    roles                                             []                 []              [get list create delete patch update watch]
    secrets                                           []                 []              [get list create delete patch update watch]
    serviceaccounts                                   []                 []              [get list create delete patch update watch]
    services/finalizers                               []                 []              [get list create delete patch update watch]
    services                                          []                 []              [get list create delete patch update watch]
    daemonsets.apps                                   []                 []              [get list create delete patch update watch]
    deployments.apps                                  []                 []              [get list create delete patch update watch]
    ingresses.apps                                    []                 []              [get list create delete patch update watch]
    replicasets.apps                                  []                 []              [get list create delete patch update watch]
    statefulsets.apps                                 []                 []              [get list create delete patch update watch]
    daemonsets.networking.k8s.io                      []                 []              [get list create delete patch update watch]
    deployments.networking.k8s.io                     []                 []              [get list create delete patch update watch]
    ingresses.networking.k8s.io                       []                 []              [get list create delete patch update watch]
    replicasets.networking.k8s.io                     []                 []              [get list create delete patch update watch]
    statefulsets.networking.k8s.io                    []                 []              [get list create delete patch update watch]
    configmaps.rbac.authorization.k8s.io              []                 []              [get list create delete patch update watch]
    endpoints.rbac.authorization.k8s.io               []                 []              [get list create delete patch update watch]
    events.rbac.authorization.k8s.io                  []                 []              [get list create delete patch update watch]
    persistentvolumeclaims.rbac.authorization.k8s.io  []                 []              [get list create delete patch update watch]
    pods.rbac.authorization.k8s.io                    []                 []              [get list create delete patch update watch]
    rolebindings.rbac.authorization.k8s.io            []                 []              [get list create delete patch update watch]
    roles.rbac.authorization.k8s.io                   []                 []              [get list create delete patch update watch]
    secrets.rbac.authorization.k8s.io                 []                 []              [get list create delete patch update watch]
    serviceaccounts.rbac.authorization.k8s.io         []                 []              [get list create delete patch update watch]
    services.rbac.authorization.k8s.io/finalizers     []                 []              [get list create delete patch update watch]
    services.rbac.authorization.k8s.io                []                 []              [get list create delete patch update watch]
    routes.route.openshift.io/custom-host             []                 []              [get list create delete patch update watch]
    routes.route.openshift.io                         []                 []              [get list create delete patch update watch]
    deployments.apps/scale                            []                 []              [patch]
    statefulsets.apps/scale                           []                 []              [patch]
    deployments.apps/finalizers                       []                 [awx-operator]  [update]
```

**Comment by shanemcd** [comment]
```
PermissionError: Invalid openshift or k8s cluster credential: (401)
```

This seems to indicate an issue with your environment. If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
