### ISSUE TITLE
pengding when sync inventory

### ISSUE THREAD

**Issue by ChuckPerry** [ansible/tower-operator#715]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Hi deer.
I run the awx-operator in my own k8s cluster, and everything seems perfect. but when I create an inventory and sync the source, it's pending forever, and the api told me the error "job_explanation": "This job is not ready to start because there is not enough available capacity.",and the detail cannot open with 
```
TypeError: Cannot read property 'status' of undefined at UA (http://XX:XX.XX.XX:32749/static/js/main.7b1f208d.chunk.js:1:1301889) at Zo (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1419511) at Ss (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1465741) at vl (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1458468) at ml (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1458393) at sl (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1455402) at http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1406773 at t.unstable_runWithPriority (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1482174) at qi (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1406482) at Yi (http://XX.XX.XX.XX:32749/static/js/2.97a1dff5.chunk.js:2:1406718)
```
thanks ahead for your reply.
##### ENVIRONMENT
* AWX version: 4.1.0
* Operator version: 19.5.0
* Kubernetes version: 1.19.2
* AWX install method: kubernetes
##### EXPECTED RESULTS

1. create a inventory with sources
```
The API INFO
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 13,
            "type": "inventory_source",
            "url": "/api/v2/inventory_sources/13/",
            "related": {
                "created_by": "/api/v2/users/1/",
                "modified_by": "/api/v2/users/1/",
                "current_job": "/api/v2/inventory_updates/46/",
                "last_job": "/api/v2/inventory_updates/45/",
                "execution_environment": "/api/v2/execution_environments/2/",
                "update": "/api/v2/inventory_sources/13/update/",
                "inventory_updates": "/api/v2/inventory_sources/13/inventory_updates/",
                "schedules": "/api/v2/inventory_sources/13/schedules/",
                "activity_stream": "/api/v2/inventory_sources/13/activity_stream/",
                "hosts": "/api/v2/inventory_sources/13/hosts/",
                "groups": "/api/v2/inventory_sources/13/groups/",
                "notification_templates_started": "/api/v2/inventory_sources/13/notification_templates_started/",
                "notification_templates_success": "/api/v2/inventory_sources/13/notification_templates_success/",
                "notification_templates_error": "/api/v2/inventory_sources/13/notification_templates_error/",
                "inventory": "/api/v2/inventories/4/",
                "source_project": "/api/v2/projects/9/",
                "current_update": "/api/v2/inventory_updates/46/",
                "last_update": "/api/v2/inventory_updates/45/"
            },
            "summary_fields": {
                "organization": {
                    "id": 2,
                    "name": "Platform",
                    "description": ""
                },
                "inventory": {
                    "id": 4,
                    "name": "K8S Cluster",
                    "description": "",
                    "has_active_failures": false,
                    "total_hosts": 0,
                    "hosts_with_active_failures": 0,
                    "total_groups": 0,
                    "has_inventory_sources": true,
                    "total_inventory_sources": 1,
                    "inventory_sources_with_failures": 1,
                    "organization_id": 2,
                    "kind": ""
                },
                "execution_environment": {
                    "id": 2,
                    "name": "Control Plane Execution Environment",
                    "description": "",
                    "image": "quay.io/ansible/awx-ee:latest"
                },
                "source_project": {
                    "id": 9,
                    "name": "Platform Project(s)",
                    "description": "",
                    "status": "successful",
                    "scm_type": "git"
                },
                "last_job": {
                    "id": 45,
                    "name": "K8S Cluster - Platform Source",
                    "description": "",
                    "finished": "2021-12-31T02:02:39.295267Z",
                    "status": "canceled",
                    "failed": true,
                    "license_error": false,
                    "canceled_on": "2021-12-31T02:02:39.295342Z"
                },
                "last_update": {
                    "id": 45,
                    "name": "K8S Cluster - Platform Source",
                    "description": "",
                    "status": "canceled",
                    "failed": true,
                    "license_error": false
                },
                "current_update": {
                    "id": 46,
                    "name": "K8S Cluster - Platform Source",
                    "description": "",
                    "status": "pending",
                    "failed": false,
                    "license_error": false
                },
                "current_job": {
                    "id": 46,
                    "name": "K8S Cluster - Platform Source",
                    "description": "",
                    "status": "pending",
                    "failed": false,
                    "license_error": false
                },
                "created_by": {
                    "id": 1,
                    "username": "admin",
                    "first_name": "",
                    "last_name": ""
                },
                "modified_by": {
                    "id": 1,
                    "username": "admin",
                    "first_name": "",
                    "last_name": ""
                },
                "user_capabilities": {
                    "edit": true,
                    "delete": true,
                    "start": true,
                    "schedule": true
                },
                "credentials": []
            },
            "created": "2021-12-30T09:27:03.935603Z",
            "modified": "2021-12-31T02:02:35.109394Z",
            "name": "Platform Source",
            "description": "",
            "source": "scm",
            "source_path": "",
            "source_vars": "---",
            "credential": null,
            "enabled_var": "",
            "enabled_value": "",
            "host_filter": "",
            "overwrite": true,
            "overwrite_vars": false,
            "custom_virtualenv": null,
            "timeout": 0,
            "verbosity": 1,
            "last_job_run": "2021-12-31T02:02:39.295267Z",
            "last_job_failed": true,
            "next_job_run": null,
            "status": "pending",
            "execution_environment": 2,
            "inventory": 4,
            "update_on_launch": false,
            "update_cache_timeout": 0,
            "source_project": 9,
            "update_on_project_update": true,
            "last_update_failed": true,
            "last_updated": "2021-12-31T02:02:39.295267Z"
        }
    ]
}
```
2. I tried to sync the project **Platform Project(s)**, it can update and download collections successfully.

##### ACTUAL RESULTS

the inventory can sync the host&groups successfully.

**Comment by shanemcd** [comment]
Hello. It looks like this might be due to a lack of resources on the system. I noticed that you seem to be running a version of the downstream product (4.1.0)... if you are a customer, please contact support and they can help you out. 

You may also have some luck troubleshooting on IRC or the mailing list.

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
