### ISSUE TITLE
AWX Task lost Postgres Connection

### ISSUE THREAD

**Issue by RichiCie** [ansible/tower-operator#761]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX Task Container lost Postgres Connection

##### ENVIRONMENT
* AWX version: 19.5
* Operator version: 0.15.0
* Kubernetes version: v1.21.5+k3s2
* AWX install method: k3s - Lightweight Kubernetes

##### STEPS TO REPRODUCE

Normal deployment and over night the AWX Task lost it's Connection to the postgres DB and Web Connection is not possible anymore.

##### EXPECTED RESULTS

Working AWX.

##### ACTUAL RESULTS

Every Pod is in running Status, only awx-task has some Log Errors at morning. 
Web Connect timed out. 

##### ADDITIONAL INFORMATION

```
kubectl get all -n awx
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/awx-operator-controller-manager-68d787cfbd-55cxr   2/2     Running   0          25h
pod/awx-postgres-0                                     1/1     Running   0          25h
pod/awx-84d5c45999-rxxdm                               4/4     Running   0          25h

NAME                                                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   xx.xx.xx.xx   <none>        8443/TCP   25h
service/awx-postgres                                      ClusterIP   None           <none>        5432/TCP   25h
service/awx-service                                       ClusterIP   xx.xx.xx.xx   <none>        80/TCP     25h

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   1/1     1            1           25h
deployment.apps/awx                               1/1     1            1           25h

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-operator-controller-manager-68d787cfbd   1         1         1       25h
replicaset.apps/awx-84d5c45999                               1         1         1       25h

NAME                            READY   AGE
statefulset.apps/awx-postgres   1/1     25h
```

##### AWX-OPERATOR LOGS

```
kubectl -n awx logs -f awx-84d5c45999-rxxdm awx-task`
...
ERROR    [124c6d98893c4e09995cff81518fad58] awx.main.dispatch.periodic encountered an error while scheduling periodic tasks
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/periodic.py", line 36, in run
    self.run_pending()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/publish.py", line 86, in apply_async
    with pg_bus_conn() as conn:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/__init__.py", line 50, in pg_bus_conn
    conn = psycopg2.connect(dbname=conf['NAME'], host=conf['HOST'], user=conf['USER'], password=conf['PASSWORD'], port=conf['PORT'], **conf.get("OPTIONS", {}))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "awx-postgres" to address: Name or service not known
...
```

**Comment by DomPolizzi** [comment]
I just faced this issue, Was the metadata name changed?

**Comment by RichiCie** [comment]
No, the metadata name was used as default:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
   name: awx
spec:
```

```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
```

**Comment by RichiCie** [comment]
Update to newest Operator Version made no change. Same behavior, issue starting over night.

##### ENVIRONMENT
* Operator version: 0.16.1

```
ERROR    [1de8f59c17da4372ba4361000c213b14] awx.main.dispatch.periodic encountered an error while scheduling periodic tasks
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/periodic.py", line 36, in run
    self.run_pending()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/publish.py", line 86, in apply_async
    with pg_bus_conn() as conn:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/dispatch/__init__.py", line 50, in pg_bus_conn
    conn = psycopg2.connect(dbname=conf['NAME'], host=conf['HOST'], user=conf['USER'], password=conf['PASSWORD'], port=conf['PORT'], **conf.get("OPTIONS", {}))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "awx-postgres" to address: Name or service not known

```

**Comment by ffirg** [comment]
@RichiCie is this still an issue for you?

**Comment by RichiCie** [comment]
> Finally it worked with a restart of coredns deployment !!! Thanks @kurokobo for all your inputs
#846 

The mentioned solution also solves my problem. A Restart of coredns.
