### ISSUE TITLE
AWX Operator Not Working With Kubernetes V1.21.5

### ISSUE THREAD

**Issue by felipe4334** [ansible/tower-operator#785]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: AWX 19.5.0
* Operator version: 0.15.0
* Kubernetes version: v1.21.5
* AWX install method: Oracle Cloud K8

##### STEPS TO REPRODUCE

Host AWX on a Kubernetes node running version v1.21.5
Run any template

##### EXPECTED RESULTS

Template to run properly.

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 107, in run
    unstream_dir(self._input, data['zipfile'], self.private_data_dir)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/utils/streaming.py", line 86, in unstream_dir
    archive.extract(info.filename, path=target_directory)
  File "/usr/lib64/python3.8/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib64/python3.8/zipfile.py", line 1700, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/lib64/python3.8/zipfile.py", line 1530, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/lib64/python3.8/zipfile.py", line 763, in read
    self._file.seek(self._pos)
OSError: [Errno 22] Invalid argument
```

##### ADDITIONAL INFORMATION

I tried running running the template on brand new cluster and awx deployment and I still get the same issue.
This appears to be an issue with Kubernetes V1.21.5 because when I reverted the nodepool back to v1.20.11 everything worked fine.

**Comment by nicko170** [comment]
Hey @felipe4334 

Seems that 0.16.1 works on 1.21.6, I just deployed it this morning.

**Comment by wasrek404** [comment]
I was also having issues with installing awx on k3s. So I switched to minikube to try the guide found on the awx-operator github page. After several failed attempts I tried an older version of the awx-operator (0.16.1) and found that that indeed worked right out of the box! I can not confirm I had the same exact traceback as OP. In my case the playbook for deploying awx kept on failing (1 failed task). "kubectl describe pods" showed me following error: "0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims" for the postgres pod. I am sure that I can reproduce this error (so I think that others can too). I used centos 8 and kubectl version v1.22.6+k3s1 as wel as version v1.23.3 with minikube.

**Comment by hijak** [comment]
This is probably due to you not having a default storageclass set?
